import { Prisma } from '@prisma/client'
import { z } from 'zod'
import { prisma } from '../../prisma'
import { audit } from '../../lib/audit'
import { HttpError, notFound } from '../../lib/errors'
import type { Ctx } from '../../lib/rbac'
import type { ClassWithRefs } from '../classes/service'
import { createCohort, patchCohort } from './schema'

export const cohortInclude = { members: { include: { class: { include: { grade: true } } } } } satisfies Prisma.CohortInclude
export type CohortWithMembers = Prisma.CohortGetPayload<{ include: typeof cohortInclude }>

export const serializeCohort = (c: CohortWithMembers) => ({
  id: c.id,
  schoolId: c.schoolId,
  academicYearId: c.academicYearId,
  name: c.name,
  gradeId: c.gradeId ?? undefined,
  type: c.type,
  autoGenerated: c.autoGenerated,
  classIds: c.members.map(m => m.classId),
  classLabels: c.members.map(m => `${m.class.grade.label}-${m.class.section}`),
})

export function list(ctx: Ctx, filter?: { academicYearId?: string; type?: string }) {
  return prisma.cohort.findMany({
    where: { schoolId: ctx.schoolId, academicYearId: filter?.academicYearId, type: filter?.type },
    include: cohortInclude,
    orderBy: [{ createdAt: 'asc' }, { id: 'asc' }],
  })
}

export async function get(ctx: Ctx, id: string) {
  const row = await prisma.cohort.findFirst({ where: { id, schoolId: ctx.schoolId }, include: cohortInclude })
  if (!row) throw notFound('Cohort')
  return row
}

// Every member class must belong to this school and share exactly `academicYearId` — a cohort must never
// span two academic years (phase-t1-timetable-foundations.md §1).
async function assertClassesInYear(ctx: Ctx, classIds: string[], academicYearId: string) {
  const rows = await prisma.class.findMany({ where: { id: { in: classIds }, schoolId: ctx.schoolId } })
  if (rows.length !== new Set(classIds).size) throw notFound('Class')
  const wrongYear = rows.filter(r => r.academicYearId !== academicYearId)
  if (wrongYear.length) {
    throw new HttpError(400, 'All cohort member classes must belong to the same academic year as the cohort', {
      academicYearId,
      offendingClassIds: wrongYear.map(r => r.id),
    })
  }
}

export async function create(ctx: Ctx, input: z.infer<typeof createCohort>) {
  if (!(await prisma.academicYear.findFirst({ where: { id: input.academicYearId, schoolId: ctx.schoolId } }))) throw notFound('Academic year')
  if (input.gradeId && !(await prisma.grade.findFirst({ where: { id: input.gradeId, schoolId: ctx.schoolId } }))) throw notFound('Grade')
  await assertClassesInYear(ctx, input.classIds, input.academicYearId)

  const row = await prisma.cohort.create({
    data: {
      schoolId: ctx.schoolId,
      academicYearId: input.academicYearId,
      name: input.name,
      gradeId: input.gradeId ?? null,
      type: input.type,
      autoGenerated: false,
      members: { create: input.classIds.map(classId => ({ classId })) },
    },
    include: cohortInclude,
  })
  await audit(ctx.schoolId, ctx.actorId, 'create', 'cohort', row.id, undefined, serializeCohort(row))
  return row
}

export async function update(ctx: Ctx, id: string, input: z.infer<typeof patchCohort>) {
  const before = await get(ctx, id)
  if (before.autoGenerated && input.classIds) {
    throw new HttpError(400, 'The auto-generated section cohort tracks its class automatically — membership cannot be edited directly')
  }
  if (input.gradeId && !(await prisma.grade.findFirst({ where: { id: input.gradeId, schoolId: ctx.schoolId } }))) throw notFound('Grade')
  if (input.classIds) await assertClassesInYear(ctx, input.classIds, before.academicYearId)

  const row = await prisma.$transaction(async tx => {
    if (input.classIds) {
      await tx.cohortClass.deleteMany({ where: { cohortId: id } })
      await tx.cohortClass.createMany({ data: input.classIds.map(classId => ({ cohortId: id, classId })) })
    }
    return tx.cohort.update({
      where: { id },
      data: { name: input.name, gradeId: input.gradeId },
      include: cohortInclude,
    })
  })
  await audit(ctx.schoolId, ctx.actorId, 'update', 'cohort', id, serializeCohort(before), serializeCohort(row))
  return row
}

export async function remove(ctx: Ctx, id: string) {
  const before = await get(ctx, id)
  if (before.autoGenerated) throw new HttpError(400, 'The auto-generated section cohort cannot be deleted directly — it is removed automatically when its class is deleted')
  await prisma.cohort.delete({ where: { id } })
  await audit(ctx.schoolId, ctx.actorId, 'delete', 'cohort', id, serializeCohort(before))
}

// ─────────────────────── auto-generation hook, called from modules/classes/service.ts ───────────────────────
// Extends the existing class-creation/-update/-delete flow rather than forking a parallel path (roadmap D2 /
// phase-t1-timetable-foundations.md §1). Not audited separately — it's folded into the class's own audit
// entry the way applyCurriculum's ClassSubject rows are.

// Idempotent: safe to call on every class create/update, and safe to re-run from the one-time backfill
// script — skips classes that already have their auto cohort.
export async function ensureSectionCohort(cls: ClassWithRefs) {
  const existing = await prisma.cohortClass.findFirst({
    where: { classId: cls.id, cohort: { autoGenerated: true, type: 'SECTION' } },
    include: { cohort: true },
  })
  const name = `${cls.grade.label}-${cls.section}`
  if (existing) {
    const c = existing.cohort
    if (c.name !== name || c.gradeId !== cls.gradeId || c.academicYearId !== cls.academicYearId) {
      await prisma.cohort.update({ where: { id: c.id }, data: { name, gradeId: cls.gradeId, academicYearId: cls.academicYearId } })
    }
    return
  }
  await prisma.cohort.create({
    data: {
      schoolId: cls.schoolId,
      academicYearId: cls.academicYearId,
      name,
      gradeId: cls.gradeId,
      type: 'SECTION',
      autoGenerated: true,
      members: { create: { classId: cls.id } },
    },
  })
}

// Called before a Class row is deleted — CohortClass cascades from Class automatically, but the now-empty
// Cohort row itself would otherwise be orphaned, so remove it explicitly.
export async function removeSectionCohortForClass(classId: string) {
  const existing = await prisma.cohortClass.findFirst({ where: { classId, cohort: { autoGenerated: true, type: 'SECTION' } } })
  if (existing) await prisma.cohort.delete({ where: { id: existing.cohortId } })
}
