import { useCallback, useEffect, useMemo, useRef, useState } from 'react'
import { toast } from 'sonner'
import { ApiError, api, errorMessage } from '../api'
import { useAcademic, useStore } from '../store'
import type {
  AutoGenerateCommitResult, AutoGenerateDraftEntry, AutoGenerateMode, AutoGenerateResult,
  PeriodDef, PeriodTemplate, Substitution, TimetableEntry,
  TeachingRequirement, TeachingAssignment, SessionDuration, RoomRequirementKind,
  AssignmentMode, TeachingAssignmentPoolMember, Preference, PreferenceScope, PreferenceProfile,
  PreferenceProfileName, RefineDraftEntry, RefineDraftResult,
  TimetableGenerationJob, RegenerateJobResult, ElectiveBlock, ElectiveChoiceResult,
  TimetableVersion, TimetableVersionStatus, TimetableLock, TimetableLockType, OverrideConflict, OverrideResult, TimetableEditEvent,
  WhatIfChangeEvent, WhatIfResult,
} from '../data'

// Data hooks and pure helpers for the timetable screens (Timetable, Timetable Builder, Overview tiles).
// Components live in src/portal/modules/timetable.tsx. See .agents/edunova/phase-2-timetable.md

/** An entry as the server returns it — `/teacher/:id` and `/me` decorate it with display names. */
export interface TimetableEntryView extends TimetableEntry { classLabel?: string; subjectName?: string; roomName?: string; teacherName?: string }
export interface ClassTimetable { template?: PeriodTemplate; entries: TimetableEntryView[]; published: boolean; publishedAt?: string }
/** `/teacher/:id` substitutions carry the affected entry (with its class/subject/room names). */
export type SubstitutionView = Substitution & { entry?: TimetableEntryView }
export interface TeacherTimetable { entries: TimetableEntryView[]; substitutions: SubstitutionView[] }
/** `/timetable/me` resolves per role, so the shape is the class view (student/parent) or the teacher view. */
export type MyTimetable = Partial<ClassTimetable> & Partial<TeacherTimetable> & { entries: TimetableEntryView[] }

/** dayOfWeek 1..6 → name. Index 0 (Sunday) is never scheduled. */
export const DAY_LABELS = ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday']
export const cellKey = (dayOfWeek: number, periodIdx: number) => `${dayOfWeek}-${periodIdx}`
export const sortedPeriods = (t: PeriodTemplate | undefined) => t ? [...t.periods].sort((a, b) => a.idx - b.idx) : []
/** Mon–Fri, plus Saturday when anything is scheduled on it (or the caller forces it). */
export const daysFor = (entries: { dayOfWeek: number }[], forceSat = false) =>
  forceSat || entries.some(e => e.dayOfWeek === 6) ? [1, 2, 3, 4, 5, 6] : [1, 2, 3, 4, 5]

export const hhmm = (d: Date) => `${String(d.getHours()).padStart(2, '0')}:${String(d.getMinutes()).padStart(2, '0')}`
export const isoDate = (d: Date) => `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}-${String(d.getDate()).padStart(2, '0')}`
/** True while `now` falls inside the period on that weekday. */
export const isRunning = (p: PeriodDef, dayOfWeek: number, now: Date) => now.getDay() === dayOfWeek && p.start <= hhmm(now) && hhmm(now) < p.end

/** Re-renders on an interval so "now" based UI (current period, next class) stays fresh. */
export function useClock(everyMs = 30_000) {
  const [now, setNow] = useState(() => new Date())
  useEffect(() => {
    const id = setInterval(() => setNow(new Date()), everyMs)
    return () => clearInterval(id)
  }, [everyMs])
  return now
}

/**
 * GET helper with cancellation: `loading` is true until the current path has answered, `data` keeps the
 * previous answer while `reload()` refetches the same path (no flicker after a save).
 */
export function useFetch<T>(path: string | null) {
  const [state, setState] = useState<{ path: string; data?: T; error?: string }>({ path: '' })
  const [nonce, setNonce] = useState(0)
  useEffect(() => {
    if (!path) return
    let cancelled = false
    api.get<T>(path)
      .then(data => { if (!cancelled) setState({ path, data }) })
      .catch(e => { if (!cancelled) setState({ path, error: errorMessage(e) }) })
    return () => { cancelled = true }
  }, [path, nonce])
  const current = path && state.path === path ? state : undefined
  return { data: current?.data, error: current?.error, loading: !!path && !current, reload: () => setNonce(n => n + 1) }
}

/** The caller's own timetable for a term (student → own class; parent → `studentId` ward; teacher → own periods). */
export function useMyTimetable(termId: string, opts: { enabled?: boolean; studentId?: string } = {}) {
  const enabled = opts.enabled ?? true
  const path = enabled && termId ? `/timetable/me?termId=${encodeURIComponent(termId)}${opts.studentId ? `&studentId=${encodeURIComponent(opts.studentId)}` : ''}` : null
  return useFetch<MyTimetable>(path)
}

/** Resolves display strings for an entry from the academic slice, preferring names the server already attached. */
export function useEntryLookup() {
  const { classSubjects, subjectById, classById, rooms } = useAcademic()
  const { db } = useStore()
  return useMemo(() => {
    const csById = new Map(classSubjects.map(cs => [cs.id, cs]))
    const roomById = new Map(rooms.map(r => [r.id, r]))
    const userById = new Map(db.users.map(u => [u.id, u]))
    const subjectRec = (e: TimetableEntryView) => { const cs = csById.get(e.classSubjectId); return cs ? subjectById.get(cs.subjectId) : undefined }
    return {
      subjectOf: (e: TimetableEntryView) => e.subjectName ?? subjectRec(e)?.name ?? 'Subject',
      colorOf: (e: TimetableEntryView) => subjectRec(e)?.color ?? '#6366f1',
      teacherOf: (e: TimetableEntryView) => e.teacherName ?? userById.get(e.teacherId ?? csById.get(e.classSubjectId)?.teacherId ?? '')?.name,
      roomOf: (e: TimetableEntryView) => e.roomName ?? (e.roomId ? roomById.get(e.roomId)?.name : undefined),
      classLabelOf: (e: TimetableEntryView) => e.classLabel ?? classById.get(e.classId)?.label,
      userName: (id?: string) => (id ? userById.get(id)?.name : undefined),
    }
  }, [classSubjects, subjectById, classById, rooms, db.users])
}
export type EntryLookup = ReturnType<typeof useEntryLookup>

// ───────────────────────────── Phase 26: auto-generate ─────────────────────────────
// See server/src/modules/timetable/autogen.ts for the exact draft/commit shapes this wraps. The endpoint
// itself never writes anything — `generate` only returns a proposal, `commit` is the one call that
// actually creates TimetableEntry rows, so the Timetable Builder always shows the draft as a distinct,
// unsaved view before either of those runs.

/** Wraps the two auto-generate POSTs with shared busy state so the builder screen doesn't duplicate it. */
export function useAutoGenerate() {
  const [busy, setBusy] = useState<'generate' | 'commit' | null>(null)
  // Phase T4 introduced the Cohort/TeachingRequirement/TeachingAssignment-scoped solver behind `cohortIds`;
  // Phase T10 §2 retired the legacy ClassSubject-scoped generator that used to run when it was omitted, so
  // `cohortIds` is required now (non-empty, enforced server-side by the schema).
  const generate = async (body: { cohortIds: string[]; termId: string; mode: AutoGenerateMode }) => {
    setBusy('generate')
    try { return await api.post<AutoGenerateResult>('/timetable/auto-generate', body) } finally { setBusy(null) }
  }
  const commit = async (body: { termId: string; mode: AutoGenerateMode; draftEntries: AutoGenerateDraftEntry[] }) => {
    setBusy('commit')
    try { return await api.post<AutoGenerateCommitResult>('/timetable/auto-generate/commit', body) } finally { setBusy(null) }
  }
  return { busy, generate, commit }
}

/**
 * Fetches each class's live grid, keyed by classId — used by the auto-generate draft review to render
 * pre-existing periods alongside newly generated ones in `fill-empty` mode (so the admin sees the whole
 * resulting grid, not just what's new). Not needed for `full-regenerate`, whose draft already stands alone.
 */
export function useGridsFor(classIds: string[], termId: string, enabled: boolean) {
  const key = enabled && termId ? classIds.slice().sort().join(',') : ''
  const [state, setState] = useState<{ key: string; data: Map<string, TimetableEntryView[]> }>({ key: '', data: new Map() })
  useEffect(() => {
    if (!key) return
    let cancelled = false
    Promise.all(classIds.map(id =>
      api.get<ClassTimetable>(`/timetable?classId=${encodeURIComponent(id)}&termId=${encodeURIComponent(termId)}`).then(d => [id, d.entries] as const),
    ))
      .then(pairs => { if (!cancelled) setState({ key, data: new Map(pairs) }) })
      .catch(() => { if (!cancelled) setState({ key, data: new Map() }) })
    return () => { cancelled = true }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [key, termId])
  return state.key === key ? state.data : new Map<string, TimetableEntryView[]>()
}

// ───────────────────────────── Phase T4: TeachingRequirement / TeachingAssignment ─────────────────────────────
// See server/src/modules/timetable/teachingRequirements.ts. Not part of `AcademicState`/`useEntity` — these
// are queried scoped to one cohort (or, for assignments, fetched whole and matched client-side) rather than
// bootstrapped whole-school, so they get their own light CRUD hooks here instead.

/** Every TeachingRequirement for one cohort (per-cohort config screen). */
export function useTeachingRequirements(cohortId: string | undefined) {
  const path = cohortId ? `/timetable/teaching-requirements?cohortId=${encodeURIComponent(cohortId)}` : null
  const { data, loading, error, reload } = useFetch<{ items: TeachingRequirement[] }>(path)
  const [busy, setBusy] = useState(false)

  const run = useCallback(async <T,>(fn: () => Promise<T>, okMsg?: string): Promise<T | null> => {
    setBusy(true)
    try {
      const out = await fn()
      reload()
      if (okMsg) toast.success(okMsg)
      return out
    } catch (e) { toast.error(errorMessage(e)); return null } finally { setBusy(false) }
  }, [reload])

  const create = useCallback((body: {
    subjectId: string; requiredPeriodsPerWeek: number; sessionDuration: SessionDuration
    roomRequirement: RoomRequirementKind; specificRoomId?: string; labDoubleAllowed: boolean
  }, okMsg?: string) => run(() =>
    api.post<{ item: TeachingRequirement }>('/timetable/teaching-requirements', { cohortId, ...body }).then(r => r.item), okMsg), [cohortId, run])

  const update = useCallback((id: string, body: Partial<Pick<TeachingRequirement,
    'requiredPeriodsPerWeek' | 'sessionDuration' | 'roomRequirement' | 'specificRoomId' | 'labDoubleAllowed'>>, okMsg?: string) =>
    run(() => api.patch<{ item: TeachingRequirement }>(`/timetable/teaching-requirements/${id}`, body).then(r => r.item), okMsg), [run])

  const remove = useCallback((id: string, okMsg?: string) =>
    run(() => api.del<{ ok: true }>(`/timetable/teaching-requirements/${id}`), okMsg), [run])

  const seedFromClassSubjects = useCallback((academicYearId: string, okMsg?: string) =>
    run(() => api.post<{ created: number; requirementIds: string[] }>('/timetable/teaching-requirements/seed-from-class-subjects', { cohortId, academicYearId }), okMsg), [cohortId, run])

  return { items: data?.items ?? [], loading, error, reload, busy, create, update, remove, seedFromClassSubjects }
}

/** Every TeachingAssignment in the school (Mode 1 Fixed is `@@unique([teachingRequirementId])`, so a flat
 * fetch + client-side match by requirement id is simpler than one request per requirement row). */
export function useTeachingAssignments() {
  const { data, loading, error, reload } = useFetch<{ items: TeachingAssignment[] }>('/timetable/teaching-assignments')
  const [busy, setBusy] = useState(false)
  const byRequirement = useMemo(() => new Map((data?.items ?? []).map(a => [a.teachingRequirementId, a])), [data])

  const assign = useCallback(async (teachingRequirementId: string, teacherId: string, selectionReason?: string) => {
    setBusy(true)
    try {
      const out = await api.post<{ item: TeachingAssignment }>('/timetable/teaching-assignments', { teachingRequirementId, teacherId, selectionReason: selectionReason || undefined })
      reload()
      toast.success('Teacher assigned')
      return out.item
    } catch (e) { toast.error(errorMessage(e)); return null } finally { setBusy(false) }
  }, [reload])

  const unassign = useCallback(async (id: string) => {
    setBusy(true)
    try { await api.del(`/timetable/teaching-assignments/${id}`); reload(); toast.success('Assignment removed'); return true }
    catch (e) { toast.error(errorMessage(e)); return false } finally { setBusy(false) }
  }, [reload])

  return { items: data?.items ?? [], loading, error, reload, busy, byRequirement, assign, unassign }
}

// ───────────────────────────── Phase T5: assignment modes 2-4, preferences, refinement ─────────────────────────────
// See .agents/edunova/phase-t5-full-solver.md and server/src/modules/timetable/{assignmentModes,preferences,
// preferenceProfiles,refinement}.ts.

/** Sets a requirement's assignmentMode (FIXED/POOL/RANDOM/OPTIMIZED) — a separate endpoint from the plain
 * PATCH used for periods/duration/room since it can invalidate an existing Fixed assignment's meaning. */
export function useSetAssignmentMode(onDone?: () => void) {
  const [busy, setBusy] = useState(false)
  const setMode = useCallback(async (id: string, mode: AssignmentMode) => {
    setBusy(true)
    try {
      const out = await api.patch<{ item: TeachingRequirement }>(`/timetable/teaching-requirements/${id}/assignment-mode`, { assignmentMode: mode })
      onDone?.()
      return out.item
    } catch (e) { toast.error(errorMessage(e)); return null } finally { setBusy(false) }
  }, [onDone])
  return { busy, setMode }
}

/** Mode 2 (Pool) — the admin-defined eligible-teacher set for one requirement. */
export function useTeachingAssignmentPool(teachingRequirementId: string | undefined) {
  const path = teachingRequirementId ? `/timetable/teaching-assignment-pool?teachingRequirementId=${encodeURIComponent(teachingRequirementId)}` : null
  const { data, loading, error, reload } = useFetch<{ items: TeachingAssignmentPoolMember[] }>(path)
  const [busy, setBusy] = useState(false)

  const add = useCallback(async (teacherId: string) => {
    if (!teachingRequirementId) return null
    setBusy(true)
    try {
      const out = await api.post<{ item: TeachingAssignmentPoolMember }>('/timetable/teaching-assignment-pool', { teachingRequirementId, teacherId })
      reload()
      return out.item
    } catch (e) { toast.error(errorMessage(e)); return null } finally { setBusy(false) }
  }, [teachingRequirementId, reload])

  const remove = useCallback(async (id: string) => {
    setBusy(true)
    try { await api.del(`/timetable/teaching-assignment-pool/${id}`); reload(); return true }
    catch (e) { toast.error(errorMessage(e)); return false } finally { setBusy(false) }
  }, [reload])

  return { items: data?.items ?? [], loading, error, reload, busy, add, remove }
}

/**
 * Explicit preview/pre-resolution for Mode 2-4 requirements: resolves (or re-resolves) the single
 * TeachingAssignment row and returns it with a real `selectionReason` — generation also auto-resolves any
 * still-unresolved requirement inline, so calling this first is optional but lets an admin review the
 * reasoning before running a full generation.
 */
export function useResolveAssignment(onDone?: () => void) {
  const [busy, setBusy] = useState(false)
  const resolve = useCallback(async (teachingRequirementId: string, termId: string) => {
    setBusy(true)
    try {
      const out = await api.post<{ item: TeachingAssignment }>('/timetable/teaching-assignments/resolve', { teachingRequirementId, termId })
      onDone?.()
      return out.item
    } catch (e) { toast.error(errorMessage(e)); return null } finally { setBusy(false) }
  }, [onDone])
  return { busy, resolve }
}

/** Preference weight rows — scope ASSIGNMENT (Mode 4's selector) or REFINEMENT (the SA engine). */
export function usePreferences(scope?: PreferenceScope) {
  const path = `/timetable/preferences${scope ? `?scope=${scope}` : ''}`
  const { data, loading, error, reload } = useFetch<{ items: Preference[] }>(path)
  const [busy, setBusy] = useState(false)

  const seedDefaults = useCallback(async () => {
    setBusy(true)
    try { await api.post('/timetable/preferences/seed-defaults', {}); reload(); toast.success('Default preference weights created') }
    catch (e) { toast.error(errorMessage(e)) } finally { setBusy(false) }
  }, [reload])

  const update = useCallback(async (type: string, body: { weight?: number; enabled?: boolean; parameters?: Record<string, unknown> }) => {
    setBusy(true)
    try {
      const out = await api.patch<{ item: Preference }>(`/timetable/preferences/${type}`, body)
      reload()
      return out.item
    } catch (e) { toast.error(errorMessage(e)); return null } finally { setBusy(false) }
  }, [reload])

  return { items: data?.items ?? [], loading, error, reload, busy, seedDefaults, update }
}

/** The 7 named PreferenceProfiles — a school activates one (pre-filling weight overrides) and can still
 * hand-adjust individual weights afterward via `usePreferences().update`. */
export function usePreferenceProfiles() {
  const { data, loading, error, reload } = useFetch<{ items: PreferenceProfile[] }>('/timetable/preference-profiles')
  const [busy, setBusy] = useState(false)

  const seedDefaults = useCallback(async () => {
    setBusy(true)
    try { await api.post('/timetable/preference-profiles/seed-defaults', {}); reload() }
    catch (e) { toast.error(errorMessage(e)) } finally { setBusy(false) }
  }, [reload])

  const activate = useCallback(async (name: PreferenceProfileName) => {
    setBusy(true)
    try {
      const out = await api.post<{ item: PreferenceProfile }>('/timetable/preference-profiles/activate', { name })
      reload()
      toast.success(`${name.replace(/_/g, ' ')} profile activated`)
      return out.item
    } catch (e) { toast.error(errorMessage(e)); return null } finally { setBusy(false) }
  }, [reload])

  const update = useCallback(async (name: PreferenceProfileName, weightOverrides: Record<string, number>) => {
    setBusy(true)
    try {
      const out = await api.patch<{ item: PreferenceProfile }>(`/timetable/preference-profiles/${name}`, { weightOverrides })
      reload()
      return out.item
    } catch (e) { toast.error(errorMessage(e)); return null } finally { setBusy(false) }
  }, [reload])

  return { items: data?.items ?? [], loading, error, reload, busy, seedDefaults, activate, update }
}

/**
 * SA refinement — an additional step after a generate call, before commit. Operates purely on the
 * in-memory draft (never touches the DB); skipping it entirely reproduces T4's original hard-constraint-
 * only behavior byte-for-byte. Only meaningful for the Cohort-group generation path (`cohortIds`) since
 * that's what decomposes cleanly by grade — see phase-t5-full-solver.md §2.
 */
export function useRefineDraft() {
  const [busy, setBusy] = useState(false)
  const refine = async (body: {
    termId: string; cohortIds: string[]; draftEntries: RefineDraftEntry[]
    preferenceProfileName?: PreferenceProfileName; timeBudgetMsPerGroup?: number; seed?: number
  }) => {
    setBusy(true)
    try { return await api.post<RefineDraftResult>('/timetable/auto-generate/refine', body) }
    finally { setBusy(false) }
  }
  return { busy, refine }
}

// ───────────────────────────── Phase T6: generation jobs, diagnostics, elective blocks ─────────────────────────────
// See .agents/edunova/phase-t6-sessions-jobs.md and server/src/modules/timetable/{jobs,diagnostics,electives}.ts.

const JOB_TERMINAL: TimetableGenerationJob['status'][] = ['COMPLETED', 'FAILED', 'CANCELLED']

/**
 * Wraps POST /generation-jobs (create+run) with a poll loop against GET /generation-jobs/:id — the job
 * currently completes synchronously within the create call (see jobs.ts), so the poll loop typically sees a
 * terminal status on its very first tick and stops immediately; it's still wired for real, since a job's
 * status/progress/currentStage are recorded faithfully row-by-row specifically so this same polling
 * mechanism keeps working unchanged once generation genuinely runs in the background at whole-school scale.
 */
export function useGenerationJob() {
  const [job, setJob] = useState<TimetableGenerationJob | null>(null)
  const [busy, setBusy] = useState<'run' | 'commit' | 'regenerate' | null>(null)
  const [error, setError] = useState<string | null>(null)
  const pollRef = useRef<number | null>(null)

  const stopPoll = useCallback(() => { if (pollRef.current) { window.clearInterval(pollRef.current); pollRef.current = null } }, [])
  useEffect(() => stopPoll, [stopPoll])

  const poll = useCallback((id: string) => {
    stopPoll()
    pollRef.current = window.setInterval(async () => {
      try {
        const res = await api.get<{ item: TimetableGenerationJob }>(`/timetable/generation-jobs/${id}`)
        setJob(res.item)
        if (JOB_TERMINAL.includes(res.item.status)) stopPoll()
      } catch { stopPoll() }
    }, 1000) as unknown as number
  }, [stopPoll])

  const run = useCallback(async (body: {
    termId: string; cohortIds: string[]; mode: AutoGenerateMode
    preferenceProfileName?: PreferenceProfileName; timeBudgetMsPerGroup?: number; seed?: number
  }) => {
    setBusy('run'); setError(null); setJob(null)
    try {
      const res = await api.post<{ item: TimetableGenerationJob }>('/timetable/generation-jobs', body)
      setJob(res.item)
      if (!JOB_TERMINAL.includes(res.item.status)) poll(res.item.id)
      return res.item
    } catch (e) { setError(errorMessage(e)); return null } finally { setBusy(null) }
  }, [poll])

  const commit = useCallback(async (jobId: string) => {
    setBusy('commit')
    try { return await api.post<AutoGenerateCommitResult>('/timetable/generation-jobs/commit', { jobId }) }
    finally { setBusy(null) }
  }, [])

  const regenerate = useCallback(async (jobId: string) => {
    setBusy('regenerate'); setError(null)
    try {
      const res = await api.post<RegenerateJobResult>(`/timetable/generation-jobs/${jobId}/regenerate`)
      setJob(res.job)
      if (!JOB_TERMINAL.includes(res.job.status)) poll(res.job.id)
      return res
    } catch (e) { setError(errorMessage(e)); return null } finally { setBusy(null) }
  }, [poll])

  const reset = useCallback(() => { stopPoll(); setJob(null); setError(null) }, [stopPoll])

  return { job, busy, error, run, commit, regenerate, reset }
}

/** Elective Blocks (§1b) — a grade-wide reserved slot, N parallel offerings. Plain list+create+commit+choose
 * CRUD, scoped by term/grade rather than bootstrapped whole-school (mirrors the TeachingRequirements hooks'
 * shape above). */
export function useElectiveBlocks(filter?: { termId?: string; gradeId?: string }) {
  const qs = new URLSearchParams()
  if (filter?.termId) qs.set('termId', filter.termId)
  if (filter?.gradeId) qs.set('gradeId', filter.gradeId)
  const query = qs.toString()
  const { data, loading, error, reload } = useFetch<{ items: ElectiveBlock[] }>(`/timetable/elective-blocks${query ? `?${query}` : ''}`)
  const [busy, setBusy] = useState(false)

  const create = useCallback(async (body: {
    termId: string; gradeId: string; name: string; dayOfWeek: number; periodIdx: number; durationPeriods: number
    offerings: { subjectId: string; teacherId: string; roomId?: string; capacity?: number }[]
  }) => {
    setBusy(true)
    try {
      const out = await api.post<{ item: ElectiveBlock }>('/timetable/elective-blocks', body)
      reload()
      toast.success('Elective block created')
      return out.item
    } catch (e) { toast.error(errorMessage(e)); return null } finally { setBusy(false) }
  }, [reload])

  const commitBlock = useCallback(async (id: string, mode: AutoGenerateMode = 'fill-empty') => {
    setBusy(true)
    try {
      const out = await api.post<AutoGenerateCommitResult>(`/timetable/elective-blocks/${id}/commit`, { mode })
      reload()
      toast.success(`Committed ${out.committed} period${out.committed === 1 ? '' : 's'}`)
      return out
    } catch (e) { toast.error(errorMessage(e)); return null } finally { setBusy(false) }
  }, [reload])

  const choose = useCallback(async (blockId: string, offeringId: string, studentId: string) => {
    setBusy(true)
    try {
      const out = await api.post<{ item: ElectiveChoiceResult }>(`/timetable/elective-blocks/${blockId}/choices`, { offeringId, studentId })
      reload()
      return out.item
    } catch (e) { toast.error(errorMessage(e)); return null } finally { setBusy(false) }
  }, [reload])

  return { items: data?.items ?? [], loading, error, reload, busy, create, commitBlock, choose }
}

// ───────────────────────────── Phase T7: versioning, locks, the override system ─────────────────────────────
// See .agents/edunova/phase-t7-versioning-override.md and server/src/modules/timetable/{versions,locks,
// overrides}.ts (source of truth). `useOverrideSession` is the one hook the upgraded Timetable Builder
// needs to know whether a class/term is currently governed by a PUBLISHED version (immutable — the legacy
// content-edit PUT /entries path is refused server-side, 409) and whether an editable draft already exists
// for it (resumed automatically on reload, never silently re-forked). Locks/move/swap/regenerate-slot/undo
// are separate small hooks below so a component only pays for what it actually renders.

const EDITABLE_VERSION_STATUSES: TimetableVersionStatus[] = ['DRAFT', 'GENERATED', 'MODIFIED', 'APPROVED']

export function useOverrideSession(classId: string, termId: string) {
  const path = classId && termId ? `/timetable/versions?termId=${encodeURIComponent(termId)}` : null
  const { data, loading, reload } = useFetch<{ items: TimetableVersion[] }>(path)
  const versions = useMemo(() => (data?.items ?? []).filter(v => v.scopeClassIds.includes(classId)), [data, classId])
  /** The version currently governing this class/term's live rows, if this scope has ever been published
   * through this system — immutable; the legacy content editor is refused for it server-side. */
  const governingPublished = useMemo(() => versions.find(v => v.status === 'PUBLISHED'), [versions])
  /** The most recent still-editable draft for this scope, if any — auto-resumed rather than re-forked. */
  const activeVersion = useMemo(
    () => versions.filter(v => EDITABLE_VERSION_STATUSES.includes(v.status)).sort((a, b) => b.createdAt.localeCompare(a.createdAt))[0],
    [versions],
  )

  const [busy, setBusy] = useState<'fork' | 'approve' | 'publish' | 'discard' | null>(null)

  const fork = useCallback(async (changeReason?: string) => {
    setBusy('fork')
    try {
      const out = await api.post<{ item: TimetableVersion }>('/timetable/versions/fork', { termId, classIds: [classId], changeReason: changeReason || undefined })
      reload()
      toast.success('Edit session started — this creates a new draft version; nothing live changes until you publish it')
      return out.item
    } catch (e) { toast.error(errorMessage(e)); return null } finally { setBusy(null) }
  }, [classId, termId, reload])

  const approve = useCallback(async (versionId: string) => {
    setBusy('approve')
    try {
      const out = await api.post<{ item: TimetableVersion }>(`/timetable/versions/${versionId}/approve`, {})
      reload()
      toast.success('Draft approved — ready to publish')
      return out.item
    } catch (e) { toast.error(errorMessage(e)); return null } finally { setBusy(null) }
  }, [reload])

  const publish = useCallback(async (versionId: string, changeReason?: string) => {
    setBusy('publish')
    try {
      const out = await api.post<{ item: TimetableVersion; archivedVersionIds: string[] }>(`/timetable/versions/${versionId}/publish`, { changeReason: changeReason || undefined })
      reload()
      toast.success('Published — this is now the live timetable')
      return out
    } catch (e) { toast.error(errorMessage(e)); return null } finally { setBusy(null) }
  }, [reload])

  const discard = useCallback(async (versionId: string) => {
    setBusy('discard')
    try {
      await api.post(`/timetable/versions/${versionId}/discard`, {})
      reload()
      toast.success('Draft discarded — the live timetable was never touched')
      return true
    } catch (e) { toast.error(errorMessage(e)); return false } finally { setBusy(null) }
  }, [reload])

  return { versions, loading, reload, governingPublished, activeVersion, busy, fork, approve, publish, discard }
}

/** Active locks for one version, plus create/release. Server enforces the granularity-specific required
 * fields (ASSIGNMENT needs targetId+day+period, TEACHER/ROOM/COHORT/SESSION need targetId, DAY needs
 * dayOfWeek) — this hook passes whatever the caller builds straight through. */
export function useVersionLocks(versionId: string | undefined) {
  const path = versionId ? `/timetable/versions/${versionId}/locks?activeOnly=true` : null
  const { data, loading, reload } = useFetch<{ items: TimetableLock[] }>(path)
  const [busy, setBusy] = useState(false)

  const createLock = useCallback(async (body: { lockType: TimetableLockType; targetType?: string; targetId?: string; dayOfWeek?: number; periodIdx?: number; reason?: string }) => {
    if (!versionId) return null
    setBusy(true)
    try {
      const out = await api.post<{ item: TimetableLock }>(`/timetable/versions/${versionId}/locks`, body)
      reload()
      toast.success('Locked')
      return out.item
    } catch (e) { toast.error(errorMessage(e)); return null } finally { setBusy(false) }
  }, [versionId, reload])

  const releaseLock = useCallback(async (lockId: string, reason?: string) => {
    setBusy(true)
    try {
      await api.post(`/timetable/locks/${lockId}/release`, { reason: reason || undefined })
      reload()
      toast.success('Unlocked')
      return true
    } catch (e) { toast.error(errorMessage(e)); return false } finally { setBusy(false) }
  }, [reload])

  return { items: data?.items ?? [], loading, reload, busy, createLock, releaseLock }
}

export interface OverrideCallResult extends OverrideResult { error?: string }

/** Every move/swap/regenerate-slot call goes through here — `dryRun: true` never throws (`ok: false` +
 * populated `conflicts`/`error` IS the live-preview signal, using the exact same check the real save runs),
 * a non-dryRun conflict surfaces the same structured 409 shape without a generic toast (the caller renders
 * it inline, same convention as the plain manual-grid save above), and any other failure (e.g. the 400 a
 * move throws when its target slot is already occupied) comes back as a plain `error` string either way. */
async function postOverride(path: string, body: Record<string, unknown>): Promise<OverrideCallResult> {
  try {
    return await api.post<OverrideResult>(path, body)
  } catch (e) {
    const conflicts = e instanceof ApiError && e.status === 409 ? (e.body as { conflicts?: OverrideConflict[] } | undefined)?.conflicts : undefined
    if (conflicts?.length) return { ok: false, conflicts }
    return { ok: false, conflicts: [], error: errorMessage(e) }
  }
}

const NO_SESSION: OverrideCallResult = { ok: false, conflicts: [], error: 'No active edit session' }

/** Move / swap / regenerate-slot for one version — `onSaved` fires only after a real (non-dryRun) success,
 * so the caller can reload the version without re-fetching on every live-preview keystroke. */
export function useOverrideActions(versionId: string | undefined, onSaved: () => void) {
  const [busy, setBusy] = useState<'move' | 'swap' | 'regenerate' | null>(null)

  const run = useCallback(async (kind: 'move' | 'swap' | 'regenerate', path: string, body: Record<string, unknown>) => {
    setBusy(kind)
    try {
      const out = await postOverride(`/timetable/versions/${versionId}/${path}`, body)
      if (!body.dryRun && out.ok) onSaved()
      return out
    } finally { setBusy(null) }
  }, [versionId, onSaved])

  const move = useCallback((body: { classId: string; fromDayOfWeek: number; fromPeriodIdx: number; toDayOfWeek: number; toPeriodIdx: number; reason?: string; dryRun?: boolean }) =>
    versionId ? run('move', 'move', body) : Promise.resolve(NO_SESSION), [versionId, run])
  const swap = useCallback((body: { a: { classId: string; dayOfWeek: number; periodIdx: number }; b: { classId: string; dayOfWeek: number; periodIdx: number }; reason?: string; dryRun?: boolean }) =>
    versionId ? run('swap', 'swap', body) : Promise.resolve(NO_SESSION), [versionId, run])
  const regenerateSlot = useCallback((body: { classId: string; dayOfWeek: number; periodIdx: number; reason?: string; dryRun?: boolean }) =>
    versionId ? run('regenerate', 'regenerate-slot', body) : Promise.resolve(NO_SESSION), [versionId, run])

  return { busy, move, swap, regenerateSlot }
}

/** Undo-last and revert-to-any-prior-point (§4's minimum bar + its stretch goal, both built for real). */
export function useUndo(versionId: string | undefined, onSaved: () => void) {
  const [busy, setBusy] = useState<'undo' | 'revert' | null>(null)

  const undo = useCallback(async () => {
    if (!versionId) return null
    setBusy('undo')
    try {
      const out = await api.post<{ ok: true; revertedEventSeq: number; entries: unknown[] }>(`/timetable/versions/${versionId}/undo`, {})
      onSaved()
      return out
    } catch (e) { toast.error(errorMessage(e)); return null } finally { setBusy(null) }
  }, [versionId, onSaved])

  const revertTo = useCallback(async (seq: number) => {
    if (!versionId) return null
    setBusy('revert')
    try {
      const out = await api.post<{ ok: true; revertedEventSeqs: number[]; entries: unknown[] }>(`/timetable/versions/${versionId}/revert-to`, { seq })
      onSaved()
      return out
    } catch (e) { toast.error(errorMessage(e)); return null } finally { setBusy(null) }
  }, [versionId, onSaved])

  return { busy, undo, revertTo }
}

/** Replicates locks.ts#lockBlocks client-side for grid/modal display purposes only (server is the real
 * enforcement, re-checked on every dryRun/save) — COHORT locks are skipped since that needs each entry's
 * cohort membership, which the builder doesn't otherwise fetch; TEACHER/ROOM/SESSION/DAY/PERIOD/ASSIGNMENT
 * (the ones a slot's own badge and the cell-actions modal actually need) are all covered. */
export function findBlockingLock(locks: TimetableLock[], e: { classSubjectId: string; teacherId: string | null; roomId: string | null; sessionId: string | null; dayOfWeek: number; periodIdx: number }): TimetableLock | undefined {
  return locks.find(l => {
    switch (l.lockType) {
      case 'TEACHER': return !!e.teacherId && l.targetId === e.teacherId
      case 'ROOM': return !!e.roomId && l.targetId === e.roomId
      case 'SESSION': return !!e.sessionId && l.targetId === e.sessionId
      case 'DAY': return l.dayOfWeek === e.dayOfWeek
      case 'PERIOD': return l.periodIdx === e.periodIdx
      case 'ASSIGNMENT': return l.targetId === e.classSubjectId && l.dayOfWeek === e.dayOfWeek && l.periodIdx === e.periodIdx
      default: return false
    }
  })
}

/** The version's ordered hand-edit log — fetched on demand (history panel), not part of the base session hook. */
export function useEditEvents(versionId: string | undefined) {
  const path = versionId ? `/timetable/versions/${versionId}/edit-events` : null
  const { data, loading, reload } = useFetch<{ items: TimetableEditEvent[] }>(path)
  return { items: data?.items ?? [], loading, reload }
}

// ───────────────────────────── Phase T8: what-if / partial re-optimization ─────────────────────────────
// See server/src/modules/timetable/whatif.ts. One call, no dryRun (unlike move/swap/regenerate-slot above)
// — a what-if run always creates a real (if disposable — Discard works on it exactly like any other draft)
// GENERATED TimetableVersion, since computing "what would the minimal patch even look like" genuinely
// requires running the real greedy+SA solver over the affected region, not a cheap conflict pre-check.
export function useWhatIf() {
  const [busy, setBusy] = useState(false)
  const run = useCallback(async (body: { versionId: string; changeEvent: WhatIfChangeEvent }): Promise<WhatIfResult | null> => {
    setBusy(true)
    try {
      return await api.post<WhatIfResult>('/timetable/what-if', body)
    } catch (e) { toast.error(errorMessage(e)); return null } finally { setBusy(false) }
  }, [])
  return { busy, run }
}

/** Today's class periods in order, split into what's running now and what comes next. */
export function todayAgenda(entries: TimetableEntryView[], template: PeriodTemplate | undefined, now: Date) {
  const day = now.getDay()
  const t = hhmm(now)
  const periods = sortedPeriods(template).filter(p => p.kind === 'class')
  const byIdx = new Map(entries.filter(e => e.dayOfWeek === day).map(e => [e.periodIdx, e]))
  const today = periods.map(p => ({ period: p, entry: byIdx.get(p.idx) })).filter((x): x is { period: PeriodDef; entry: TimetableEntryView } => !!x.entry)
  const running = today.find(x => x.period.start <= t && t < x.period.end)
  const next = today.find(x => x.period.start > t)
  return { today, running, next }
}
