import { useEffect, useMemo, useState } from 'react'
import { AlertCircle, ArrowLeft, Banknote, CreditCard, Download, Landmark, QrCode, Receipt as ReceiptIcon, ShieldCheck, Smartphone, Wallet } from 'lucide-react'
import { toDataURL } from 'qrcode'
import { useStore } from '@/lib/store'
import { fmtINR, type Receipt } from '@/lib/data'
import { Card, Empty, Field, Modal, PageHead, Pill, TermTabs, inputCls, statusTone } from '../ui'
import { useTerm } from '../Portal'
import { toast } from 'sonner'

/* ── helpers ───────────────────────────────────────────── */

function useIsMobile() {
  const [isMobile, setIsMobile] = useState(() => window.matchMedia('(max-width: 1023px)').matches)
  useEffect(() => {
    const mq = window.matchMedia('(max-width: 1023px)')
    const fn = () => setIsMobile(mq.matches)
    mq.addEventListener('change', fn)
    return () => mq.removeEventListener('change', fn)
  }, [])
  return isMobile
}

function normalizeCard(s: string) {
  return s.replace(/\D/g, '').slice(0, 16)
}

function formatCard(s: string) {
  return normalizeCard(s).replace(/(.{4})/g, '$1 ').trim()
}

function validExpiry(v: string) {
  if (!/^\d{2}\/\d{2}$/.test(v)) return false
  const [mm, yy] = v.split('/').map(Number)
  if (mm < 1 || mm > 12) return false
  const now = new Date()
  const year = 2000 + yy
  if (year < now.getFullYear()) return false
  if (year === now.getFullYear() && mm < now.getMonth() + 1) return false
  return true
}

const BANKS = ['State Bank of India', 'HDFC Bank', 'ICICI Bank', 'Axis Bank', 'Canara Bank', 'Bank of Baroda', 'Kotak Mahindra Bank']

const UPI_APPS = ['Google Pay', 'PhonePe', 'Paytm', 'Amazon Pay']

/* ── module: payment gateway (desktop only) ──────────────── */

export function PaymentGatewayMod() {
  const { db, update, user } = useStore()
  const { term, setTerm } = useTerm()
  const isMobile = useIsMobile()
  const rows = db.receipts.filter(r => r.kind === 'fee' && r.term === term)
  const total = rows.reduce((a, r) => a + r.amount, 0)
  const dueTotal = rows.filter(r => r.status === 'Due').reduce((a, r) => a + r.amount, 0)

  const [payOpen, setPayOpen] = useState(false)
  const [selectedReceipt, setSelectedReceipt] = useState<Receipt | null>(null)
  const [tab, setTab] = useState<'upi' | 'card' | 'netbanking'>('upi')

  const [upiQr, setUpiQr] = useState('')
  const [upiPaid, setUpiPaid] = useState(false)
  const [upiVerifying, setUpiVerifying] = useState(false)

  const [cardNumber, setCardNumber] = useState('')
  const [cardExpiry, setCardExpiry] = useState('')
  const [cardCvv, setCardCvv] = useState('')
  const [cardName, setCardName] = useState('')
  const [cardErrors, setCardErrors] = useState<string[]>([])
  const [cardProcessing, setCardProcessing] = useState(false)

  const [bank, setBank] = useState(BANKS[0])
  const [nbProcessing, setNbProcessing] = useState(false)

  const studentName = useMemo(() => {
    if (user?.role === 'student') return user.name
    if (user?.role === 'parent') {
      const child = db.users.find(u => u.role === 'student' && u.parentEmail === user.email)
      return child?.name ?? 'Aarav Sharma'
    }
    return 'Aarav Sharma'
  }, [user, db.users])

  const openPay = (r: Receipt) => {
    setSelectedReceipt(r)
    setTab('upi')
    setUpiPaid(false)
    setUpiVerifying(false)
    setCardNumber('')
    setCardExpiry('')
    setCardCvv('')
    setCardName('')
    setCardErrors([])
    setCardProcessing(false)
    setBank(BANKS[0])
    setNbProcessing(false)
    setPayOpen(true)
  }

  useEffect(() => {
    if (!selectedReceipt || !payOpen) return
    const upi = `upi://pay?pa=edunova@icici&pn=EduNova%20School&am=${selectedReceipt.amount}&cu=INR&tr=${selectedReceipt.id}`
    toDataURL(upi, { width: 200, margin: 2, color: { dark: '#1e1b4b', light: '#ffffff' } })
      .then(setUpiQr)
      .catch(() => setUpiQr(''))
  }, [selectedReceipt, payOpen])

  const downloadReceipt = (r: Receipt) => {
    const lines = [
      'EduNova School · Official Payment Receipt',
      '----------------------------------------',
      `Receipt #: ${r.id}`,
      `Student: ${studentName}`,
      `Fee head: ${r.label}`,
      `Amount: ${fmtINR(r.amount)}`,
      `Status: ${r.status}`,
      `Date: ${new Date(r.date).toLocaleDateString('en-IN')}`,
      `Term: ${term.toUpperCase()}`,
      '----------------------------------------',
      'This is a simulated receipt generated by the EduNova demo.',
      `Generated: ${new Date().toLocaleString('en-IN')}`,
    ]
    const blob = new Blob([lines.join('\n')], { type: 'text/plain' })
    const a = document.createElement('a')
    a.href = URL.createObjectURL(blob)
    a.download = `Receipt_${r.id}_${r.label.replace(/\W+/g, '_')}.txt`
    a.click()
    URL.revokeObjectURL(a.href)
  }

  const completePayment = (r: Receipt) => {
    update(d => {
      const rec = d.receipts.find(x => x.id === r.id)
      if (rec) {
        rec.status = 'Paid'
        rec.date = new Date().toISOString().slice(0, 10)
      }
      return d
    })
    setPayOpen(false)
    setSelectedReceipt(null)
    downloadReceipt(r)
    toast.success('Payment successful — receipt downloaded')
  }

  const verifyUPI = () => {
    setUpiPaid(true)
    setUpiVerifying(true)
    setTimeout(() => {
      setUpiVerifying(false)
      if (selectedReceipt) completePayment(selectedReceipt)
    }, 1500)
  }

  const payCard = () => {
    const errors: string[] = []
    if (normalizeCard(cardNumber).length !== 16) errors.push('Card number must be 16 digits')
    if (!validExpiry(cardExpiry)) errors.push('Enter a valid future expiry date (MM/YY)')
    if (cardCvv.length !== 3) errors.push('CVV must be 3 digits')
    if (!cardName.trim()) errors.push('Cardholder name is required')
    if (errors.length > 0) {
      setCardErrors(errors)
      return
    }
    setCardErrors([])
    setCardProcessing(true)
    setTimeout(() => {
      setCardProcessing(false)
      if (selectedReceipt) completePayment(selectedReceipt)
    }, 1500)
  }

  const payNetBanking = () => {
    setNbProcessing(true)
    setTimeout(() => {
      setNbProcessing(false)
      if (selectedReceipt) completePayment(selectedReceipt)
    }, 1500)
  }

  return (
    <div>
      <PageHead title="Payment Gateway" sub={isMobile ? 'View dues and receipts. Payments are enabled on desktop.' : `Pay fees securely for ${studentName}`}>
        <TermTabs terms={db.terms} term={term} setTerm={setTerm} />
      </PageHead>

      {isMobile && (
        <Card className="mb-5 border-amber-200 bg-amber-50/50 dark:bg-amber-500/5">
          <div className="flex items-start gap-3">
            <Smartphone className="mt-0.5 text-amber-600" size={20} />
            <div>
              <p className="text-[14px] font-semibold text-amber-800 dark:text-amber-200">Desktop-only payments</p>
              <p className="mt-1 text-[13px] text-amber-700/80 dark:text-amber-200/70">For security, fee payments are available on desktop. You can still view all dues and receipts here.</p>
            </div>
          </div>
        </Card>
      )}

      <div className="mb-5 grid gap-4 sm:grid-cols-3">
        <Card className="flex items-center gap-4">
          <span className="flex h-11 w-11 items-center justify-center rounded-2xl bg-indigo-50"><Wallet size={20} className="text-indigo-600" /></span>
          <div><p className="text-[12px] uppercase tracking-wider text-black/40 dark:text-white/40">Total this term</p><p className="font-display text-2xl font-medium">{fmtINR(total)}</p></div>
        </Card>
        <Card className="flex items-center gap-4">
          <span className="flex h-11 w-11 items-center justify-center rounded-2xl bg-emerald-50"><ShieldCheck size={20} className="text-emerald-600" /></span>
          <div><p className="text-[12px] uppercase tracking-wider text-black/40 dark:text-white/40">Paid</p><p className="font-display text-2xl font-medium">{fmtINR(rows.filter(r => r.status === 'Paid').reduce((a, r) => a + r.amount, 0))}</p></div>
        </Card>
        <Card className="flex items-center gap-4">
          <span className="flex h-11 w-11 items-center justify-center rounded-2xl bg-amber-50"><Banknote size={20} className="text-amber-600" /></span>
          <div><p className="text-[12px] uppercase tracking-wider text-black/40 dark:text-white/40">Due</p><p className="font-display text-2xl font-medium">{fmtINR(dueTotal)}</p></div>
        </Card>
      </div>

      <Card className="p-0">
        {rows.map(r => (
          <div key={r.id} className="flex flex-wrap items-center gap-4 border-b border-black/[.05] dark:border-white/[.07] px-6 py-4 last:border-0">
            <span className={`flex h-10 w-10 items-center justify-center rounded-xl ${r.status === 'Paid' ? 'bg-emerald-50 text-emerald-600' : 'bg-amber-50 text-amber-600'}`}>
              <ReceiptIcon size={18} />
            </span>
            <div className="min-w-48 flex-1">
              <p className="text-[14.5px] font-semibold">{r.label}</p>
              <p className="text-[12.5px] text-black/45 dark:text-white/45">{new Date(r.date).toLocaleDateString('en-IN', { day: 'numeric', month: 'short', year: 'numeric' })}</p>
            </div>
            <p className="text-[15px] font-bold">{fmtINR(r.amount)}</p>
            <Pill tone={statusTone(r.status)}>{r.status}</Pill>
            <div className="flex gap-2">
              {r.status === 'Due' && !isMobile && (
                <button onClick={() => openPay(r)} className="flex items-center gap-1.5 rounded-full bg-indigo-600 px-4 py-2 text-[12.5px] font-semibold text-white hover:bg-indigo-700">
                  <CreditCard size={13} /> Pay
                </button>
              )}
              {r.status === 'Paid' && (
                <button onClick={() => downloadReceipt(r)} className="flex items-center gap-1.5 rounded-full bg-black/[.06] dark:bg-white/[.08] px-4 py-2 text-[12.5px] font-semibold hover:bg-black/10 dark:hover:bg-white/15">
                  <Download size={13} /> Receipt
                </button>
              )}
            </div>
          </div>
        ))}
        {rows.length === 0 && <div className="p-6"><Empty text="Nothing here for this term." /></div>}
      </Card>

      <Modal open={payOpen} onClose={() => { if (!cardProcessing && !nbProcessing && !upiVerifying) setPayOpen(false) }} title={`Pay ${selectedReceipt ? fmtINR(selectedReceipt.amount) : ''}`} wide>
        {selectedReceipt && (
          <div className="space-y-4">
            <div className="flex items-center gap-3 rounded-2xl bg-indigo-50 p-4 dark:bg-indigo-500/10">
              <ReceiptIcon className="text-indigo-600" size={22} />
              <div className="flex-1">
                <p className="text-[13.5px] font-semibold text-indigo-900 dark:text-indigo-100">{selectedReceipt.label}</p>
                <p className="text-[12.5px] text-indigo-700/80 dark:text-indigo-200/70">{studentName} · {fmtINR(selectedReceipt.amount)}</p>
              </div>
            </div>

            <div className="flex gap-2">
              {(['upi', 'card', 'netbanking'] as const).map(t => (
                <button key={t} onClick={() => setTab(t)}
                  className={`flex flex-1 items-center justify-center gap-2 rounded-xl py-2.5 text-[13px] font-semibold transition-colors ${tab === t ? 'bg-black text-white' : 'bg-black/[.05] dark:bg-white/[.07] text-black/60 dark:text-white/60 hover:bg-black/10 dark:hover:bg-white/15'}`}>
                  {t === 'upi' && <QrCode size={15} />}
                  {t === 'card' && <CreditCard size={15} />}
                  {t === 'netbanking' && <Landmark size={15} />}
                  {t === 'upi' ? 'UPI' : t === 'card' ? 'Card' : 'Net Banking'}
                </button>
              ))}
            </div>

            {tab === 'upi' && (
              <div className="space-y-4">
                <div className="flex flex-col items-center gap-4 rounded-2xl border border-black/[.08] dark:border-white/[.10] p-6">
                  {upiQr ? <img src={upiQr} alt="UPI QR" className="h-44 w-44 rounded-xl" /> : <div className="flex h-44 w-44 items-center justify-center rounded-xl bg-black/[.05] dark:bg-white/[.07]"><QrCode size={48} className="text-black/30 dark:text-white/30" /></div>}
                  <p className="text-center text-[13px] font-semibold text-black/70 dark:text-white/70">Scan with any UPI app</p>
                  <div className="flex flex-wrap justify-center gap-2">
                    {UPI_APPS.map(app => (
                      <span key={app} className="rounded-full bg-black/[.05] dark:bg-white/[.07] px-3 py-1 text-[11.5px] font-semibold text-black/60 dark:text-white/60">{app}</span>
                    ))}
                  </div>
                </div>
                <button onClick={verifyUPI} disabled={upiVerifying} className="btn-ink flex w-full items-center justify-center gap-2 py-3 text-[14px] font-semibold disabled:opacity-40">
                  {upiVerifying ? 'Verifying…' : upiPaid ? 'I have paid' : 'I have completed the payment'}
                </button>
                <p className="text-center text-[12px] text-black/40 dark:text-white/40">This is a simulated gateway. No real money is deducted.</p>
              </div>
            )}

            {tab === 'card' && (
              <div className="space-y-4">
                <div className="rounded-2xl border border-black/[.08] dark:border-white/[.10] bg-gradient-to-br from-slate-800 to-slate-900 p-5 text-white shadow-lg">
                  <div className="flex items-start justify-between">
                    <CreditCard size={28} />
                    <span className="text-[11px] font-bold uppercase tracking-wider">EduNova Gateway</span>
                  </div>
                  <p className="mt-6 font-mono text-[18px] tracking-widest">{cardNumber ? formatCard(cardNumber) : '•••• •••• •••• ••••'}</p>
                  <div className="mt-4 flex justify-between text-[12px] uppercase tracking-wider">
                    <span>{cardName || 'CARDHOLDER NAME'}</span>
                    <span>{cardExpiry || 'MM/YY'}</span>
                  </div>
                </div>
                <div className="grid gap-3 sm:grid-cols-2">
                  <Field label="Card number">
                    <input value={formatCard(cardNumber)} onChange={e => setCardNumber(normalizeCard(e.target.value))} placeholder="0000 0000 0000 0000" maxLength={19} className={inputCls} inputMode="numeric" />
                  </Field>
                  <Field label="Cardholder name">
                    <input value={cardName} onChange={e => setCardName(e.target.value.replace(/[^a-zA-Z\s]/g, ''))} placeholder="Name on card" className={inputCls} />
                  </Field>
                  <Field label="Expiry (MM/YY)">
                    <input value={cardExpiry} onChange={e => {
                      let v = e.target.value.replace(/\D/g, '').slice(0, 4)
                      if (v.length >= 2) v = v.slice(0, 2) + '/' + v.slice(2)
                      setCardExpiry(v)
                    }} placeholder="MM/YY" maxLength={5} className={inputCls} inputMode="numeric" />
                  </Field>
                  <Field label="CVV">
                    <input value={cardCvv} onChange={e => setCardCvv(e.target.value.replace(/\D/g, '').slice(0, 3))} placeholder="123" maxLength={3} className={inputCls} inputMode="numeric" type="password" />
                  </Field>
                </div>
                {cardErrors.length > 0 && (
                  <div className="rounded-2xl bg-rose-50 p-3 text-[12.5px] text-rose-700 dark:bg-rose-500/10 dark:text-rose-200">
                    {cardErrors.map((e, i) => <p key={i} className="flex items-center gap-1.5"><AlertCircle size={12} /> {e}</p>)}
                  </div>
                )}
                <button onClick={payCard} disabled={cardProcessing} className="btn-ink flex w-full items-center justify-center gap-2 py-3 text-[14px] font-semibold disabled:opacity-40">
                  {cardProcessing ? 'Processing…' : `Pay ${fmtINR(selectedReceipt.amount)}`}
                </button>
                <p className="text-center text-[12px] text-black/40 dark:text-white/40">Simulated card validation. No real transaction occurs.</p>
              </div>
            )}

            {tab === 'netbanking' && (
              <div className="space-y-4">
                <div className="rounded-2xl border border-black/[.08] dark:border-white/[.10] p-4">
                  <p className="mb-3 text-[13px] font-semibold text-black/60 dark:text-white/60">Select your bank</p>
                  <div className="grid gap-2 sm:grid-cols-2">
                    {BANKS.map(b => (
                      <button key={b} onClick={() => setBank(b)}
                        className={`flex items-center justify-between rounded-xl border px-4 py-3 text-left text-[13px] font-semibold transition-colors ${bank === b ? 'border-indigo-500 bg-indigo-50 text-indigo-700 dark:bg-indigo-500/10 dark:text-indigo-200' : 'border-black/[.08] dark:border-white/[.10] hover:bg-black/[.03] dark:hover:bg-white/[.05]'}`}>
                        <span className="flex items-center gap-2"><Landmark size={15} /> {b}</span>
                        {bank === b && <ShieldCheck size={16} />}
                      </button>
                    ))}
                  </div>
                </div>
                <button onClick={payNetBanking} disabled={nbProcessing} className="btn-ink flex w-full items-center justify-center gap-2 py-3 text-[14px] font-semibold disabled:opacity-40">
                  {nbProcessing ? 'Redirecting to bank…' : `Pay ${fmtINR(selectedReceipt.amount)} via ${bank}`}
                </button>
                <p className="text-center text-[12px] text-black/40 dark:text-white/40">You will be redirected to the bank login page (simulated).</p>
              </div>
            )}

            <button onClick={() => setPayOpen(false)} disabled={cardProcessing || nbProcessing || upiVerifying} className="flex w-full items-center justify-center gap-2 rounded-full py-2 text-[13px] font-semibold text-black/50 dark:text-white/50 hover:bg-black/[.05] dark:hover:bg-white/[.07] disabled:opacity-40">
              <ArrowLeft size={14} /> Cancel and return
            </button>
          </div>
        )}
      </Modal>
    </div>
  )
}
