-- AlterTable
ALTER TABLE "PeriodTemplate" ADD COLUMN     "baseTemplateId" TEXT,
ADD COLUMN     "dayOfWeek" INTEGER;

-- AlterTable
ALTER TABLE "User" ADD COLUMN     "affinitySource" TEXT NOT NULL DEFAULT 'DECLARED',
ADD COLUMN     "declaredBandAffinity" JSONB,
ADD COLUMN     "verifiedBandAffinity" JSONB;

-- CreateTable
CREATE TABLE "Cohort" (
    "id" TEXT NOT NULL,
    "schoolId" TEXT NOT NULL,
    "academicYearId" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "gradeId" TEXT,
    "type" TEXT NOT NULL,
    "autoGenerated" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "Cohort_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "CohortClass" (
    "id" TEXT NOT NULL,
    "cohortId" TEXT NOT NULL,
    "classId" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "CohortClass_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Capability" (
    "id" TEXT NOT NULL,
    "schoolId" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "code" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "Capability_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "RoomCapability" (
    "id" TEXT NOT NULL,
    "roomId" TEXT NOT NULL,
    "capabilityId" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "RoomCapability_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "TeacherQualification" (
    "id" TEXT NOT NULL,
    "schoolId" TEXT NOT NULL,
    "teacherId" TEXT NOT NULL,
    "subjectId" TEXT NOT NULL,
    "gradeRangeMin" INTEGER NOT NULL,
    "gradeRangeMax" INTEGER NOT NULL,
    "proficiency" TEXT NOT NULL,
    "isPrimarySubject" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "TeacherQualification_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "WorkingDayPattern" (
    "id" TEXT NOT NULL,
    "schoolId" TEXT NOT NULL,
    "academicYearId" TEXT NOT NULL,
    "workingDays" JSONB NOT NULL,
    "saturdayPattern" TEXT NOT NULL DEFAULT 'NONE',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "WorkingDayPattern_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "Cohort_schoolId_idx" ON "Cohort"("schoolId");

-- CreateIndex
CREATE INDEX "Cohort_academicYearId_idx" ON "Cohort"("academicYearId");

-- CreateIndex
CREATE INDEX "CohortClass_classId_idx" ON "CohortClass"("classId");

-- CreateIndex
CREATE UNIQUE INDEX "CohortClass_cohortId_classId_key" ON "CohortClass"("cohortId", "classId");

-- CreateIndex
CREATE INDEX "Capability_schoolId_idx" ON "Capability"("schoolId");

-- CreateIndex
CREATE UNIQUE INDEX "Capability_schoolId_code_key" ON "Capability"("schoolId", "code");

-- CreateIndex
CREATE INDEX "RoomCapability_capabilityId_idx" ON "RoomCapability"("capabilityId");

-- CreateIndex
CREATE UNIQUE INDEX "RoomCapability_roomId_capabilityId_key" ON "RoomCapability"("roomId", "capabilityId");

-- CreateIndex
CREATE INDEX "TeacherQualification_schoolId_idx" ON "TeacherQualification"("schoolId");

-- CreateIndex
CREATE INDEX "TeacherQualification_teacherId_idx" ON "TeacherQualification"("teacherId");

-- CreateIndex
CREATE INDEX "TeacherQualification_subjectId_idx" ON "TeacherQualification"("subjectId");

-- CreateIndex
CREATE UNIQUE INDEX "TeacherQualification_teacherId_subjectId_gradeRangeMin_grad_key" ON "TeacherQualification"("teacherId", "subjectId", "gradeRangeMin", "gradeRangeMax");

-- CreateIndex
CREATE INDEX "WorkingDayPattern_schoolId_idx" ON "WorkingDayPattern"("schoolId");

-- CreateIndex
CREATE UNIQUE INDEX "WorkingDayPattern_schoolId_academicYearId_key" ON "WorkingDayPattern"("schoolId", "academicYearId");

-- CreateIndex
CREATE INDEX "PeriodTemplate_baseTemplateId_idx" ON "PeriodTemplate"("baseTemplateId");

-- AddForeignKey
ALTER TABLE "PeriodTemplate" ADD CONSTRAINT "PeriodTemplate_baseTemplateId_fkey" FOREIGN KEY ("baseTemplateId") REFERENCES "PeriodTemplate"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Cohort" ADD CONSTRAINT "Cohort_schoolId_fkey" FOREIGN KEY ("schoolId") REFERENCES "School"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Cohort" ADD CONSTRAINT "Cohort_academicYearId_fkey" FOREIGN KEY ("academicYearId") REFERENCES "AcademicYear"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Cohort" ADD CONSTRAINT "Cohort_gradeId_fkey" FOREIGN KEY ("gradeId") REFERENCES "Grade"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "CohortClass" ADD CONSTRAINT "CohortClass_cohortId_fkey" FOREIGN KEY ("cohortId") REFERENCES "Cohort"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "CohortClass" ADD CONSTRAINT "CohortClass_classId_fkey" FOREIGN KEY ("classId") REFERENCES "Class"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Capability" ADD CONSTRAINT "Capability_schoolId_fkey" FOREIGN KEY ("schoolId") REFERENCES "School"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "RoomCapability" ADD CONSTRAINT "RoomCapability_roomId_fkey" FOREIGN KEY ("roomId") REFERENCES "Room"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "RoomCapability" ADD CONSTRAINT "RoomCapability_capabilityId_fkey" FOREIGN KEY ("capabilityId") REFERENCES "Capability"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TeacherQualification" ADD CONSTRAINT "TeacherQualification_schoolId_fkey" FOREIGN KEY ("schoolId") REFERENCES "School"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TeacherQualification" ADD CONSTRAINT "TeacherQualification_teacherId_fkey" FOREIGN KEY ("teacherId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TeacherQualification" ADD CONSTRAINT "TeacherQualification_subjectId_fkey" FOREIGN KEY ("subjectId") REFERENCES "Subject"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "WorkingDayPattern" ADD CONSTRAINT "WorkingDayPattern_schoolId_fkey" FOREIGN KEY ("schoolId") REFERENCES "School"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "WorkingDayPattern" ADD CONSTRAINT "WorkingDayPattern_academicYearId_fkey" FOREIGN KEY ("academicYearId") REFERENCES "AcademicYear"("id") ON DELETE CASCADE ON UPDATE CASCADE;
