import { describe, it, expect, beforeAll } from 'vitest'
import request from 'supertest'
import { createApp } from '../src/app'
import { buildFixture, type Fixture } from './helpers/fixtures'
import { authHeader } from './helpers/auth'

// Phase T6 — sessions, generation jobs, diagnostics (phase-t6-sessions-jobs.md). Covers: SharedSession
// (2 cohorts, 1 session, non-colliding materialization + a genuine double-booking still caught), ElectiveBlock
// (2 parallel offerings, student choices, non-colliding materialization), TimetableGenerationJob (structured
// infeasibility diagnostics with real numbers, and regenerate reproducibility).

const app = createApp()
let fx: Fixture
let cohortAId: string
let cohortBId: string
let secondClassId: string
let engReqA: string
let engReqB: string

const PERIOD_TEMPLATE = {
  name: 'T6 Standard Day',
  periods: [
    { idx: 0, label: 'P1', start: '08:00', end: '08:45', kind: 'class' },
    { idx: 1, label: 'P2', start: '08:45', end: '09:30', kind: 'class' },
    { idx: 2, label: 'P3', start: '09:30', end: '10:15', kind: 'class' },
    { idx: 3, label: 'P4', start: '10:15', end: '11:00', kind: 'class' },
  ],
}

beforeAll(async () => {
  fx = await buildFixture(app)
  await request(app).post('/api/timetable/period-templates').set(authHeader(fx.tokens.superadmin)).send(PERIOD_TEMPLATE)
  await request(app).post('/api/timetable/constraints/seed-defaults').set(authHeader(fx.tokens.admin))

  const cls = await request(app).post('/api/academic/classes').set(authHeader(fx.tokens.superadmin))
    .send({ academicYearId: fx.ids.yearId, boardId: fx.ids.boardId, gradeId: fx.ids.gradeId, section: 'B', capacity: 2 })
  secondClassId = cls.body.item.id
  await request(app).post('/api/academic/class-subjects').set(authHeader(fx.tokens.superadmin))
    .send({ classId: secondClassId, subjectId: fx.ids.subjectId, teacherId: fx.ids.teacherId, periodsPerWeek: 5 })

  const cohorts = await request(app).get('/api/academic/cohorts').query({ academicYearId: fx.ids.yearId }).set(authHeader(fx.tokens.admin))
  cohortAId = cohorts.body.items.find((c: { autoGenerated: boolean; classIds: string[] }) => c.autoGenerated && c.classIds.includes(fx.ids.classId)).id
  cohortBId = cohorts.body.items.find((c: { autoGenerated: boolean; classIds: string[] }) => c.autoGenerated && c.classIds.includes(secondClassId)).id

  // Both cohorts' subject requirement, taught by the SAME fixture teacher — the exact "12-A + 12-B combined
  // English" shape the SharedSession spec example describes.
  const reqA = await request(app).post('/api/timetable/teaching-requirements').set(authHeader(fx.tokens.admin))
    .send({ cohortId: cohortAId, subjectId: fx.ids.subjectId, requiredPeriodsPerWeek: 4 })
  engReqA = reqA.body.item.id
  await request(app).post('/api/timetable/teaching-assignments').set(authHeader(fx.tokens.admin))
    .send({ teachingRequirementId: engReqA, teacherId: fx.ids.teacherId })

  const reqB = await request(app).post('/api/timetable/teaching-requirements').set(authHeader(fx.tokens.admin))
    .send({ cohortId: cohortBId, subjectId: fx.ids.subjectId, requiredPeriodsPerWeek: 4 })
  engReqB = reqB.body.item.id
  await request(app).post('/api/timetable/teaching-assignments').set(authHeader(fx.tokens.admin))
    .send({ teachingRequirementId: engReqB, teacherId: fx.ids.teacherId })
})

describe('T6 §1 — SharedSession', () => {
  it('links 2 cohorts to one session, satisfying both requirements at once', async () => {
    const res = await request(app).post('/api/timetable/sessions/shared').set(authHeader(fx.tokens.admin)).send({
      termId: fx.ids.termId, requirementIds: [engReqA, engReqB], dayOfWeek: 1, periodIdx: 0, durationPeriods: 1,
    })
    expect(res.status).toBe(201)
    expect(res.body.item.isShared).toBe(true)
    expect(res.body.item.cohortIds.sort()).toEqual([cohortAId, cohortBId].sort())
  })

  it('teacher cannot create a shared session; admin can', async () => {
    const res = await request(app).post('/api/timetable/sessions/shared').set(authHeader(fx.tokens.teacher)).send({
      termId: fx.ids.termId, requirementIds: [engReqA, engReqB], dayOfWeek: 1, periodIdx: 1, durationPeriods: 1,
    })
    expect(res.status).toBe(403)
  })

  it('rejects requirements from the same cohort (not a real SharedSession)', async () => {
    const otherSubject = await request(app).post('/api/academic/subjects').set(authHeader(fx.tokens.superadmin))
      .send({ name: 'Geography', code: 'GEO', color: '#22c55e' })
    const secondReqSameCohort = await request(app).post('/api/timetable/teaching-requirements').set(authHeader(fx.tokens.admin))
      .send({ cohortId: cohortAId, subjectId: otherSubject.body.item.id, requiredPeriodsPerWeek: 1 })
    const res = await request(app).post('/api/timetable/sessions/shared').set(authHeader(fx.tokens.admin)).send({
      termId: fx.ids.termId, requirementIds: [engReqA, secondReqSameCohort.body.item.id], dayOfWeek: 1, periodIdx: 2, durationPeriods: 1,
    })
    expect(res.status).toBe(400)
  })

  it('commits into TimetableEntry — one row per underlying class, same teacher/slot, same sessionId, not treated as a collision', async () => {
    const created = await request(app).post('/api/timetable/sessions/shared').set(authHeader(fx.tokens.admin)).send({
      termId: fx.ids.termId, requirementIds: [engReqA, engReqB], dayOfWeek: 2, periodIdx: 0, durationPeriods: 1,
    })
    const sessionId = created.body.item.id

    const commit = await request(app).post('/api/timetable/sessions/commit').set(authHeader(fx.tokens.admin))
      .send({ termId: fx.ids.termId, sessionIds: [sessionId], mode: 'fill-empty' })
    expect(commit.status).toBe(200)
    expect(commit.body.committed).toBe(2)

    const gridA = await request(app).get('/api/timetable').query({ classId: fx.ids.classId, termId: fx.ids.termId }).set(authHeader(fx.tokens.admin))
    const gridB = await request(app).get('/api/timetable').query({ classId: secondClassId, termId: fx.ids.termId }).set(authHeader(fx.tokens.admin))
    const entryA = gridA.body.entries.find((e: { dayOfWeek: number; periodIdx: number }) => e.dayOfWeek === 2 && e.periodIdx === 0)
    const entryB = gridB.body.entries.find((e: { dayOfWeek: number; periodIdx: number }) => e.dayOfWeek === 2 && e.periodIdx === 0)
    expect(entryA.teacherId).toBe(fx.ids.teacherId)
    expect(entryB.teacherId).toBe(fx.ids.teacherId)
    expect(entryA.sessionId).toBe(sessionId)
    expect(entryB.sessionId).toBe(sessionId)
  })

  it('a genuine double-booking of that same teacher/slot (no sessionId) is still rejected as a real conflict', async () => {
    // Day 2 period 0 is now the SharedSession's slot for the fixture teacher — try to also book them
    // (manually, no sessionId) into a third class at the exact same slot.
    const thirdCs = await request(app).post('/api/academic/class-subjects').set(authHeader(fx.tokens.superadmin))
      .send({ classId: secondClassId, subjectId: fx.ids.subjectId, teacherId: fx.ids.teacherId, periodsPerWeek: 5 }).catch(() => null)
    void thirdCs
    const res = await request(app).put('/api/timetable/entries').set(authHeader(fx.tokens.admin)).send({
      classId: fx.ids.classId, termId: fx.ids.termId,
      entries: [
        { dayOfWeek: 2, periodIdx: 0, classSubjectId: fx.ids.classSubjectId, teacherId: fx.ids.teacherId },
      ],
    })
    // classId here is fx.ids.classId itself, whose OWN row at that slot is the shared session's entry — this
    // PUT replaces its whole grid, re-validating; since the entry re-submitted has no sessionId, it must
    // still resolve to a conflict against secondClassId's sibling row (same teacher/slot, different session).
    expect(res.status).toBe(409)
    expect(res.body.conflicts[0].rule).toBe('teacher')
  })
})

describe('T6 §1b — ElectiveBlock', () => {
  let blockId: string
  let offeringAId: string
  let offeringBId: string
  let secondSubjectId: string
  let secondTeacherId: string

  beforeAll(async () => {
    const subj = await request(app).post('/api/academic/subjects').set(authHeader(fx.tokens.superadmin))
      .send({ name: 'Art', code: 'ART', color: '#f472b6' })
    secondSubjectId = subj.body.item.id
    const teacher = await request(app).post('/api/users').set(authHeader(fx.tokens.superadmin)).send({ role: 'teacher', name: 'Art Teacher' })
    secondTeacherId = teacher.body.user.id
  })

  it('creates a block with 2 parallel offerings, each its own cohort/requirement/session', async () => {
    const res = await request(app).post('/api/timetable/elective-blocks').set(authHeader(fx.tokens.admin)).send({
      termId: fx.ids.termId, gradeId: fx.ids.gradeId, name: 'Grade Electives', dayOfWeek: 3, periodIdx: 0, durationPeriods: 1,
      offerings: [
        { subjectId: fx.ids.subjectId, teacherId: fx.ids.teacherId },
        { subjectId: secondSubjectId, teacherId: secondTeacherId },
      ],
    })
    expect(res.status).toBe(201)
    expect(res.body.item.offerings).toHaveLength(2)
    blockId = res.body.item.id
    offeringAId = res.body.item.offerings[0].id
    offeringBId = res.body.item.offerings[1].id
  })

  it('the same teacher cannot run two parallel offerings in one block', async () => {
    const res = await request(app).post('/api/timetable/elective-blocks').set(authHeader(fx.tokens.admin)).send({
      termId: fx.ids.termId, gradeId: fx.ids.gradeId, name: 'Bad Block', dayOfWeek: 3, periodIdx: 1, durationPeriods: 1,
      offerings: [
        { subjectId: fx.ids.subjectId, teacherId: fx.ids.teacherId },
        { subjectId: secondSubjectId, teacherId: fx.ids.teacherId },
      ],
    })
    expect(res.status).toBe(400)
  })

  it('students are individually bucketed into different offerings with zero clash', async () => {
    const c1 = await request(app).post(`/api/timetable/elective-blocks/${blockId}/choices`).set(authHeader(fx.tokens.admin))
      .send({ offeringId: offeringAId, studentId: fx.ids.studentId })
    expect(c1.status).toBe(201)
    expect(c1.body.item.status).toBe('Registered')

    // A second student for offering B — reuse the parent's ward if distinct, else the same student can't be
    // in both; verify a student already Registered in offering A is rejected from also joining offering B.
    const c2 = await request(app).post(`/api/timetable/elective-blocks/${blockId}/choices`).set(authHeader(fx.tokens.admin))
      .send({ offeringId: offeringBId, studentId: fx.ids.studentId })
    expect(c2.status).toBe(409)
  })

  it('commits into TimetableEntry — the grade\'s base classes get a placeholder row, offerings/choices stay authoritative and unmaterialized-per-class', async () => {
    const res = await request(app).post(`/api/timetable/elective-blocks/${blockId}/commit`).set(authHeader(fx.tokens.admin)).send({ mode: 'fill-empty' })
    expect(res.status).toBe(200)
    expect(res.body.committed).toBeGreaterThan(0)

    const grid = await request(app).get('/api/timetable').query({ classId: fx.ids.classId, termId: fx.ids.termId }).set(authHeader(fx.tokens.admin))
    const entry = grid.body.entries.find((e: { dayOfWeek: number; periodIdx: number }) => e.dayOfWeek === 3 && e.periodIdx === 0)
    expect(entry).toBeTruthy()
    expect(entry.teacherId).toBeUndefined()

    const block = await request(app).get(`/api/timetable/elective-blocks/${blockId}`).set(authHeader(fx.tokens.admin))
    expect(block.body.item.offerings[0].registered + block.body.item.offerings[1].registered).toBe(1)
  })
})

describe('T6 §3 — TimetableGenerationJob', () => {
  it('completes with real placements for a satisfiable scope', async () => {
    const res = await request(app).post('/api/timetable/generation-jobs').set(authHeader(fx.tokens.admin)).send({
      termId: fx.ids.termId, cohortIds: [cohortAId], mode: 'fill-empty', timeBudgetMsPerGroup: 200, seed: 7,
    })
    expect(res.status).toBe(201)
    expect(res.body.item.status).toBe('COMPLETED')
    expect(res.body.item.outputHash).toBeTruthy()
    expect(res.body.item.solverVersion).toBeTruthy()
  })

  it('produces structured, real-numbered diagnostics for an intentionally infeasible scope', async () => {
    // Blow the cohort's total weekly demand far past its own period-template capacity (4 periods/day x 4
    // days visible to this fixture's template — see PERIOD_TEMPLATE above).
    await request(app).patch(`/api/timetable/teaching-requirements/${engReqA}`).set(authHeader(fx.tokens.admin)).send({ requiredPeriodsPerWeek: 60 })

    const res = await request(app).post('/api/timetable/generation-jobs').set(authHeader(fx.tokens.admin)).send({
      termId: fx.ids.termId, cohortIds: [cohortAId], mode: 'full-regenerate', timeBudgetMsPerGroup: 200, seed: 7,
    })
    expect(res.status).toBe(201)
    expect(Array.isArray(res.body.item.diagnostics)).toBe(true)
    expect(res.body.item.diagnostics.length).toBeGreaterThan(0)
    const capacity = res.body.item.diagnostics.find((d: { type: string }) => d.type === 'CAPACITY_EXCEEDED')
    expect(capacity).toBeTruthy()
    expect(capacity.requiredPeriodsPerWeek).toBeGreaterThan(capacity.availablePeriodsPerWeek)
    expect(capacity.suggestedActions.length).toBeGreaterThan(0)

    // Restore for later tests in this file.
    await request(app).patch(`/api/timetable/teaching-requirements/${engReqA}`).set(authHeader(fx.tokens.admin)).send({ requiredPeriodsPerWeek: 4 })
  })

  it('regenerating the same job twice produces byte-identical output (reproducibility)', async () => {
    const created = await request(app).post('/api/timetable/generation-jobs').set(authHeader(fx.tokens.admin)).send({
      termId: fx.ids.termId, cohortIds: [cohortAId], mode: 'fill-empty', timeBudgetMsPerGroup: 150, seed: 99,
    })
    const jobId = created.body.item.id

    const regen1 = await request(app).post(`/api/timetable/generation-jobs/${jobId}/regenerate`).set(authHeader(fx.tokens.admin))
    const regen2 = await request(app).post(`/api/timetable/generation-jobs/${jobId}/regenerate`).set(authHeader(fx.tokens.admin))
    expect(regen1.status).toBe(200)
    expect(regen2.status).toBe(200)
    expect(regen1.body.newOutputHash).toBeTruthy()
    expect(regen1.body.newOutputHash).toBe(regen2.body.newOutputHash)
  })
})
