import { describe, it, expect, beforeAll } from 'vitest'
import request from 'supertest'
import { createApp } from '../src/app'
import { buildFixture, type Fixture } from './helpers/fixtures'
import { authHeader } from './helpers/auth'

// Phase T4 — Constraint Builder + solver core (phase-t4-solver-core.md). Covers: TeachingRequirement
// seeding from existing ClassSubject.periodsPerWeek data, TeachingAssignment (Mode 1 Fixed), Constraint
// Builder default seeding, the cohort-scoped generation path, and — critically — that Phase 26's existing
// class-scoped "Auto-Generate" keeps working completely unchanged when `cohortIds` is not sent.

const app = createApp()
let fx: Fixture
let cohortAId: string
let cohortBId: string
let secondClassId: string
let chemSubjectId: string
let labRoomId: string
let chemTeacherId: string

const PERIOD_TEMPLATE = {
  name: 'T4 Standard Day',
  periods: [
    { idx: 0, label: 'P1', start: '08:00', end: '08:45', kind: 'class' },
    { idx: 1, label: 'P2', start: '08:45', end: '09:30', kind: 'class' },
    { idx: 2, label: 'P3', start: '09:30', end: '10:15', kind: 'class' },
    { idx: 3, label: 'P4', start: '10:15', end: '11:00', kind: 'class' },
  ],
}

beforeAll(async () => {
  fx = await buildFixture(app)

  // A period template is required before any generation can place anything (same prerequisite as the
  // legacy generator) — this becomes the school default (first template created).
  await request(app).post('/api/timetable/period-templates').set(authHeader(fx.tokens.superadmin)).send(PERIOD_TEMPLATE)

  // A second section (VIII-B) plus a lab subject, taught by the SAME teacher across both sections — the
  // "teacher who teaches multiple cohorts" scenario the spec's live-verification requirement calls for.
  const cls = await request(app).post('/api/academic/classes').set(authHeader(fx.tokens.superadmin))
    .send({ academicYearId: fx.ids.yearId, boardId: fx.ids.boardId, gradeId: fx.ids.gradeId, section: 'B', capacity: 2 })
  secondClassId = cls.body.item.id

  const chemTeacher = await request(app).post('/api/users').set(authHeader(fx.tokens.superadmin)).send({ role: 'teacher', name: 'Priya Chem' })
  chemTeacherId = chemTeacher.body.user.id

  const chemSubject = await request(app).post('/api/academic/subjects').set(authHeader(fx.tokens.superadmin))
    .send({ name: 'Chemistry', code: 'CHEM', color: '#22c55e' })
  chemSubjectId = chemSubject.body.item.id

  const lab = await request(app).post('/api/academic/rooms').set(authHeader(fx.tokens.superadmin)).send({ name: 'Lab 1', kind: 'lab', capacity: 30 })
  labRoomId = lab.body.item.id

  // VIII-A already has Mathematics (5/week, fx.ids.teacherId) from buildFixture. Add Chemistry (4/week,
  // needs a lab double) to both VIII-A and VIII-B, same teacher on both — this is what makes the scenario
  // "genuinely constrained": Priya cannot be double-booked across A and B, and both compete for Lab 1.
  await request(app).post('/api/academic/class-subjects').set(authHeader(fx.tokens.superadmin))
    .send({ classId: fx.ids.classId, subjectId: chemSubjectId, teacherId: chemTeacherId, periodsPerWeek: 4 })
  await request(app).post('/api/academic/class-subjects').set(authHeader(fx.tokens.superadmin))
    .send({ classId: secondClassId, subjectId: fx.ids.subjectId, teacherId: fx.ids.teacherId, periodsPerWeek: 5 })
  await request(app).post('/api/academic/class-subjects').set(authHeader(fx.tokens.superadmin))
    .send({ classId: secondClassId, subjectId: chemSubjectId, teacherId: chemTeacherId, periodsPerWeek: 4 })

  const cohorts = await request(app).get('/api/academic/cohorts').query({ academicYearId: fx.ids.yearId }).set(authHeader(fx.tokens.admin))
  cohortAId = cohorts.body.items.find((c: { autoGenerated: boolean; classIds: string[] }) => c.autoGenerated && c.classIds.includes(fx.ids.classId)).id
  cohortBId = cohorts.body.items.find((c: { autoGenerated: boolean; classIds: string[] }) => c.autoGenerated && c.classIds.includes(secondClassId)).id
})

describe('T4 §3 — Constraint Builder: default seeding', () => {
  it('seeds the default HARD constraint catalog, idempotently', async () => {
    const res = await request(app).post('/api/timetable/constraints/seed-defaults').set(authHeader(fx.tokens.admin))
    expect(res.status).toBe(200)
    expect(res.body.added).toBeGreaterThan(0)
    const again = await request(app).post('/api/timetable/constraints/seed-defaults').set(authHeader(fx.tokens.admin))
    expect(again.body.added).toBe(0)
  })

  it('lists the seeded constraints, all enabled and HARD, source SYSTEM', async () => {
    const res = await request(app).get('/api/timetable/constraints').set(authHeader(fx.tokens.admin))
    expect(res.status).toBe(200)
    expect(res.body.items.length).toBeGreaterThanOrEqual(6)
    for (const c of res.body.items) {
      expect(c.severity).toBe('HARD')
      expect(c.source).toBe('SYSTEM')
      expect(c.enabled).toBe(true)
    }
  })

  it('teacher cannot seed or write constraints; admin can', async () => {
    const res = await request(app).post('/api/timetable/constraints').set(authHeader(fx.tokens.teacher)).send({ type: 'TEACHER_COLLISION' })
    expect(res.status).toBe(403)
  })

  it('a SYSTEM constraint cannot be deleted, only disabled', async () => {
    const list = await request(app).get('/api/timetable/constraints').set(authHeader(fx.tokens.admin))
    const row = list.body.items.find((c: { type: string }) => c.type === 'TEACHER_COLLISION')
    const del = await request(app).delete(`/api/timetable/constraints/${row.id}`).set(authHeader(fx.tokens.admin))
    expect(del.status).toBe(400)
  })
})

describe('T4 §1 — TeachingRequirement: seeded from existing ClassSubject.periodsPerWeek', () => {
  it('seeding creates one requirement per (cohort, subject) matching the existing periodsPerWeek exactly', async () => {
    const res = await request(app).post('/api/timetable/teaching-requirements/seed-from-class-subjects')
      .set(authHeader(fx.tokens.admin)).send({ academicYearId: fx.ids.yearId })
    expect(res.status).toBe(200)
    expect(res.body.created).toBeGreaterThanOrEqual(4) // Math+Chem for A, Math+Chem for B

    const reqsA = await request(app).get('/api/timetable/teaching-requirements').query({ cohortId: cohortAId }).set(authHeader(fx.tokens.admin))
    const math = reqsA.body.items.find((r: { subjectId: string }) => r.subjectId === fx.ids.subjectId)
    const chem = reqsA.body.items.find((r: { subjectId: string }) => r.subjectId === chemSubjectId)
    expect(math.requiredPeriodsPerWeek).toBe(5) // matches the fixture's ClassSubject periodsPerWeek exactly
    expect(chem.requiredPeriodsPerWeek).toBe(4)
    expect(chem.sessionDuration).toBe('DOUBLE') // lab-name heuristic (reused from autogen.ts's needsLab)
    expect(chem.roomRequirement).toBe('LAB_TYPE')
  })

  it('re-seeding is idempotent (existing requirements are not duplicated or overwritten)', async () => {
    const before = await request(app).get('/api/timetable/teaching-requirements').query({ cohortId: cohortAId }).set(authHeader(fx.tokens.admin))
    const res = await request(app).post('/api/timetable/teaching-requirements/seed-from-class-subjects')
      .set(authHeader(fx.tokens.admin)).send({ academicYearId: fx.ids.yearId })
    expect(res.body.created).toBe(0)
    const after = await request(app).get('/api/timetable/teaching-requirements').query({ cohortId: cohortAId }).set(authHeader(fx.tokens.admin))
    expect(after.body.items).toHaveLength(before.body.items.length)
  })

  it('seeding also creates the Fixed TeachingAssignment from the existing ClassSubject.teacherId', async () => {
    const reqsA = await request(app).get('/api/timetable/teaching-requirements').query({ cohortId: cohortAId }).set(authHeader(fx.tokens.admin))
    const chem = reqsA.body.items.find((r: { subjectId: string }) => r.subjectId === chemSubjectId)
    const assignments = await request(app).get('/api/timetable/teaching-assignments').query({ teachingRequirementId: chem.id }).set(authHeader(fx.tokens.admin))
    expect(assignments.body.items).toHaveLength(1)
    expect(assignments.body.items[0].teacherId).toBe(chemTeacherId)
    expect(assignments.body.items[0].assignmentMode).toBe('FIXED')
  })

  it('teacher cannot create a teaching requirement; admin can', async () => {
    const res = await request(app).post('/api/timetable/teaching-requirements').set(authHeader(fx.tokens.teacher))
      .send({ cohortId: cohortAId, subjectId: fx.ids.subjectId, requiredPeriodsPerWeek: 3 })
    expect(res.status).toBe(403)
  })

  it('rejects a duplicate (cohort, subject) requirement', async () => {
    const res = await request(app).post('/api/timetable/teaching-requirements').set(authHeader(fx.tokens.admin))
      .send({ cohortId: cohortAId, subjectId: fx.ids.subjectId, requiredPeriodsPerWeek: 3 })
    expect(res.status).toBe(409)
  })
})

describe('T4 §2 — TeachingAssignment: Fixed mode only', () => {
  it('a second Fixed assignment on the same requirement is rejected (one Fixed assignment per requirement, this phase)', async () => {
    const reqsA = await request(app).get('/api/timetable/teaching-requirements').query({ cohortId: cohortAId }).set(authHeader(fx.tokens.admin))
    const math = reqsA.body.items.find((r: { subjectId: string }) => r.subjectId === fx.ids.subjectId)
    const res = await request(app).post('/api/timetable/teaching-assignments').set(authHeader(fx.tokens.admin))
      .send({ teachingRequirementId: math.id, teacherId: chemTeacherId })
    expect(res.status).toBe(409)
  })
})

describe('T4 §4 — cohort-scoped generation: genuinely constrained scenario', () => {
  it('generates a full-week draft for both cohorts with zero hard-constraint violations', async () => {
    const res = await request(app).post('/api/timetable/auto-generate').set(authHeader(fx.tokens.admin)).send({
      cohortIds: [cohortAId, cohortBId], termId: fx.ids.termId, mode: 'full-regenerate',
    })
    expect(res.status).toBe(200)
    expect(res.body.unplaced).toEqual([]) // 24 slots/class capacity comfortably covers 5+4 periods/week
    expect(res.body.draftEntries.length).toBeGreaterThan(0)

    // Re-run the existing conflict-detection logic by hand over the draft: no teacher, room, or class is
    // double-booked at the same (day, period) — the exact hard constraints TEACHER_COLLISION/
    // ROOM_COLLISION/COHORT_COLLISION exist to enforce.
    type Entry = { classId: string; dayOfWeek: number; periodIdx: number; teacherId?: string; roomId?: string }
    const bySlot = (key: (e: Entry) => string | undefined) => {
      const seen = new Map<string, number>()
      for (const e of res.body.draftEntries as Entry[]) {
        const k = key(e)
        if (!k) continue
        const slot = `${k}@${e.dayOfWeek}:${e.periodIdx}`
        seen.set(slot, (seen.get(slot) ?? 0) + 1)
      }
      return [...seen.values()].filter(c => c > 1).length
    }
    expect(bySlot(e => e.teacherId)).toBe(0)
    expect(bySlot(e => e.roomId)).toBe(0)
    expect(bySlot(e => e.classId)).toBe(0)

    // Priya (the shared Chemistry teacher) genuinely appears across both VIII-A and VIII-B in the draft —
    // proving the multi-cohort teacher scenario was exercised, not accidentally skipped.
    const priyaClasses = new Set((res.body.draftEntries as Entry[]).filter(e => e.teacherId === chemTeacherId).map(e => e.classId))
    expect(priyaClasses.has(fx.ids.classId)).toBe(true)
    expect(priyaClasses.has(secondClassId)).toBe(true)

    // Every Chemistry placement used the lab room (roomRequirement=LAB_TYPE was honored).
    const chemEntries = (res.body.draftEntries as (Entry & { classSubjectId: string })[]).filter(e => e.teacherId === chemTeacherId)
    expect(chemEntries.length).toBeGreaterThan(0)
    expect(chemEntries.every(e => e.roomId === labRoomId)).toBe(true)

    // Commit through the exact same path Phase 26's UI uses — proves the two generation paths share one
    // write path (service.ts#replaceGrid → validateGrid), not a parallel conflict engine.
    const commit = await request(app).post('/api/timetable/auto-generate/commit').set(authHeader(fx.tokens.admin)).send({
      termId: fx.ids.termId, mode: 'full-regenerate', draftEntries: res.body.draftEntries,
    })
    expect(commit.status).toBe(200)

    const grid = await request(app).get('/api/timetable').query({ classId: fx.ids.classId, termId: fx.ids.termId }).set(authHeader(fx.tokens.admin))
    expect(grid.body.entries.length).toBeGreaterThan(0)
  })

  it('a requirement with no TeachingAssignment yet is reported as unplaced, not silently dropped', async () => {
    const bio = await request(app).post('/api/academic/subjects').set(authHeader(fx.tokens.superadmin)).send({ name: 'Biology', code: 'BIO', color: '#f59e0b' })
    const req = await request(app).post('/api/timetable/teaching-requirements').set(authHeader(fx.tokens.admin))
      .send({ cohortId: cohortAId, subjectId: bio.body.item.id, requiredPeriodsPerWeek: 3 })
    expect(req.status).toBe(201)

    const res = await request(app).post('/api/timetable/auto-generate').set(authHeader(fx.tokens.admin)).send({
      cohortIds: [cohortAId], termId: fx.ids.termId, mode: 'fill-empty',
    })
    expect(res.status).toBe(200)
    const unplacedBio = res.body.unplaced.find((u: { subjectName: string }) => u.subjectName === 'Biology')
    expect(unplacedBio).toBeTruthy()
    expect(unplacedBio.reason).toMatch(/no teacher assigned/i)
  })
})

// Phase T10 §2 — Phase 26's legacy ClassSubject-scoped generator (auto-generate with `classId` or with
// neither `classId` nor `cohortIds`) was retired now that the Cohort/TeachingRequirement-scoped solver
// covers the same ground (every class has an auto-generated 1:1 cohort — D2) plus soft constraints,
// diagnostics, and sessions the legacy path never had. `cohortIds` is required by the schema now, so the
// two tests that lived here (asserting the legacy classId-scoped and whole-year-omitted behaviors) no
// longer have anything to exercise — removed rather than kept as dead/always-400 assertions. Equivalent
// coverage for "single class" and "every class" scope now exists via the cohort-scoped describe block
// immediately above (a cohort can be exactly one class's auto-generated section cohort, or many).
describe('T10 §2 regression — the legacy Auto-Generate endpoint shape is gone', () => {
  it('classId (no cohortIds) is now rejected by validation, not silently routed to a legacy generator', async () => {
    const res = await request(app).post('/api/timetable/auto-generate').set(authHeader(fx.tokens.admin)).send({
      classId: fx.ids.classId, termId: fx.ids.termId, mode: 'fill-empty',
    })
    expect(res.status).toBe(400)
  })

  it('omitting cohortIds entirely is rejected', async () => {
    const res = await request(app).post('/api/timetable/auto-generate').set(authHeader(fx.tokens.admin)).send({
      termId: fx.ids.termId, mode: 'fill-empty',
    })
    expect(res.status).toBe(400)
  })
})
