import { describe, it, expect, beforeAll } from 'vitest'
import request from 'supertest'
import { createApp } from '../src/app'
import { buildFixture, type Fixture } from './helpers/fixtures'
import { authHeader, login } from './helpers/auth'

// Phase T5 — full assignment modes + soft constraints (phase-t5-full-solver.md). Covers: Modes 2-4
// (Pool/Random/Optimized) resolution + explainable selectionReason, TeacherAvailability, Preference /
// PreferenceProfile CRUD + seeding, SA refinement (incremental scoring, hard-safety invariant, measurable
// improvement), and the critical regression check that T4's FIXED-mode + Phase 26's legacy generator both
// still work unchanged.

const app = createApp()
let fx: Fixture
let cohortAId: string
let mathReqId: string
let chemReqId: string
let chemSubjectId: string
let chemTeacher1Id: string
let chemTeacher2Id: string
let chemTeacher2Token: string
let labRoomId: string

const PERIOD_TEMPLATE = {
  name: 'T5 Standard Day',
  periods: [
    { idx: 0, label: 'P1', start: '08:00', end: '08:45', kind: 'class' },
    { idx: 1, label: 'P2', start: '08:45', end: '09:30', kind: 'class' },
    { idx: 2, label: 'P3', start: '09:30', end: '10:15', kind: 'class' },
    { idx: 3, label: 'P4', start: '10:15', end: '11:00', kind: 'class' },
    { idx: 4, label: 'P5', start: '11:15', end: '12:00', kind: 'class' },
    { idx: 5, label: 'P6', start: '12:00', end: '12:45', kind: 'class' },
  ],
}

beforeAll(async () => {
  fx = await buildFixture(app)
  await request(app).post('/api/timetable/period-templates').set(authHeader(fx.tokens.superadmin)).send(PERIOD_TEMPLATE)
  // Same prerequisite as T4's own solverCore.test.ts — without the active HARD-constraint catalog,
  // generation performs no teacher/room/cohort collision checking at all.
  await request(app).post('/api/timetable/constraints/seed-defaults').set(authHeader(fx.tokens.admin))

  const chemSubject = await request(app).post('/api/academic/subjects').set(authHeader(fx.tokens.superadmin))
    .send({ name: 'Chemistry', code: 'CHEM', color: '#22c55e' })
  chemSubjectId = chemSubject.body.item.id

  const lab = await request(app).post('/api/academic/rooms').set(authHeader(fx.tokens.superadmin)).send({ name: 'Lab 1', kind: 'lab', capacity: 30 })
  labRoomId = lab.body.item.id

  const t1 = await request(app).post('/api/users').set(authHeader(fx.tokens.superadmin)).send({ role: 'teacher', name: 'Chem Teacher One' })
  chemTeacher1Id = t1.body.user.id
  const t2 = await request(app).post('/api/users').set(authHeader(fx.tokens.superadmin)).send({ role: 'teacher', name: 'Chem Teacher Two' })
  chemTeacher2Id = t2.body.user.id
  const chemTeacher2Login = await login(app, t2.body.user.email, t2.body.password)
  chemTeacher2Token = chemTeacher2Login.token

  // T1 qualifications for both candidate teachers — Mode 3/4's eligibility universe.
  await request(app).post('/api/academic/teacher-qualifications').set(authHeader(fx.tokens.superadmin))
    .send({ teacherId: chemTeacher1Id, subjectId: chemSubjectId, gradeRangeMin: 1, gradeRangeMax: 12, proficiency: 'PRIMARY', isPrimarySubject: true })
    .then(r => { if (r.status >= 400) throw new Error(`qual1 failed: ${r.status} ${JSON.stringify(r.body)}`) })
  await request(app).post('/api/academic/teacher-qualifications').set(authHeader(fx.tokens.superadmin))
    .send({ teacherId: chemTeacher2Id, subjectId: chemSubjectId, gradeRangeMin: 1, gradeRangeMax: 12, proficiency: 'SECONDARY', isPrimarySubject: false })

  const cohorts = await request(app).get('/api/academic/cohorts').query({ academicYearId: fx.ids.yearId }).set(authHeader(fx.tokens.admin))
  cohortAId = cohorts.body.items.find((c: { autoGenerated: boolean; classIds: string[] }) => c.autoGenerated && c.classIds.includes(fx.ids.classId)).id

  await request(app).post('/api/timetable/teaching-requirements/seed-from-class-subjects')
    .set(authHeader(fx.tokens.admin)).send({ academicYearId: fx.ids.yearId })
  const reqs = await request(app).get('/api/timetable/teaching-requirements').query({ cohortId: cohortAId }).set(authHeader(fx.tokens.admin))
  mathReqId = reqs.body.items.find((r: { subjectId: string }) => r.subjectId === fx.ids.subjectId).id

  const chemReq = await request(app).post('/api/timetable/teaching-requirements').set(authHeader(fx.tokens.admin))
    .send({ cohortId: cohortAId, subjectId: chemSubjectId, requiredPeriodsPerWeek: 4, sessionDuration: 'DOUBLE', roomRequirement: 'LAB_TYPE', labDoubleAllowed: true })
  chemReqId = chemReq.body.item.id
})

describe('T5 §1 — Assignment Mode 2 (Pool)', () => {
  it('a requirement with no pool members cannot resolve', async () => {
    await request(app).patch(`/api/timetable/teaching-requirements/${chemReqId}/assignment-mode`).set(authHeader(fx.tokens.admin)).send({ assignmentMode: 'POOL' })
    const res = await request(app).post('/api/timetable/teaching-assignments/resolve').set(authHeader(fx.tokens.admin))
      .send({ teachingRequirementId: chemReqId, termId: fx.ids.termId })
    expect(res.status).toBe(400)
  })

  it('resolves to the lowest-workload pool member, with an explainable reason', async () => {
    await request(app).post('/api/timetable/teaching-assignment-pool').set(authHeader(fx.tokens.admin)).send({ teachingRequirementId: chemReqId, teacherId: chemTeacher1Id })
    await request(app).post('/api/timetable/teaching-assignment-pool').set(authHeader(fx.tokens.admin)).send({ teachingRequirementId: chemReqId, teacherId: chemTeacher2Id })
    const res = await request(app).post('/api/timetable/teaching-assignments/resolve').set(authHeader(fx.tokens.admin))
      .send({ teachingRequirementId: chemReqId, termId: fx.ids.termId })
    expect(res.status).toBe(200)
    expect([chemTeacher1Id, chemTeacher2Id]).toContain(res.body.item.teacherId)
    expect(res.body.item.assignmentMode).toBe('POOL')
    expect(res.body.item.selectionReason).toMatch(/pool mode/i)
    expect(res.body.item.selectionReason).toMatch(/workload/i)
  })

  it('teacher cannot add to the pool; admin can', async () => {
    const res = await request(app).post('/api/timetable/teaching-assignment-pool').set(authHeader(fx.tokens.teacher)).send({ teachingRequirementId: chemReqId, teacherId: chemTeacher1Id })
    expect(res.status).toBe(403)
  })
})

describe('T5 §1 — Assignment Mode 3 (Random)', () => {
  it('selects among T1-qualification-eligible teachers only, with a reason naming the eligible pool size', async () => {
    await request(app).patch(`/api/timetable/teaching-requirements/${chemReqId}/assignment-mode`).set(authHeader(fx.tokens.admin)).send({ assignmentMode: 'RANDOM' })
    const res = await request(app).post('/api/timetable/teaching-assignments/resolve').set(authHeader(fx.tokens.admin))
      .send({ teachingRequirementId: chemReqId, termId: fx.ids.termId })
    expect(res.status).toBe(200)
    expect([chemTeacher1Id, chemTeacher2Id]).toContain(res.body.item.teacherId)
    expect(res.body.item.assignmentMode).toBe('RANDOM')
    expect(res.body.item.selectionReason).toMatch(/random mode/i)
  })
})

describe('T5 §1 — Assignment Mode 4 (Optimized) with real T1 qualification + band-affinity data', () => {
  it('prefers the PRIMARY-proficiency, primary-subject teacher over the SECONDARY one, with a genuinely explainable reason', async () => {
    await request(app).patch(`/api/timetable/teaching-requirements/${chemReqId}/assignment-mode`).set(authHeader(fx.tokens.admin)).send({ assignmentMode: 'OPTIMIZED' })
    const res = await request(app).post('/api/timetable/teaching-assignments/resolve').set(authHeader(fx.tokens.admin))
      .send({ teachingRequirementId: chemReqId, termId: fx.ids.termId })
    expect(res.status).toBe(200)
    expect(res.body.item.teacherId).toBe(chemTeacher1Id) // PRIMARY + isPrimarySubject beats SECONDARY
    expect(res.body.item.assignmentMode).toBe('OPTIMIZED')
    // Explainable, not generic boilerplate: names the actual signals considered.
    expect(res.body.item.selectionReason).toMatch(/optimized mode/i)
    expect(res.body.item.selectionReason).toMatch(/qualified|primary/i)
    expect(res.body.item.selectionReason.length).toBeGreaterThan(40)
  })

  it('gives an honest "no band-affinity match" fallback message when the cohort has no band data', async () => {
    const res = await request(app).post('/api/timetable/teaching-assignments/resolve').set(authHeader(fx.tokens.admin))
      .send({ teachingRequirementId: chemReqId, termId: fx.ids.termId })
    expect(res.status).toBe(200)
    expect(res.body.item.selectionReason).toMatch(/no band-affinity match/i)
  })

  it('a teacher can self-declare band affinity, and Mode 4 reads it without erroring', async () => {
    // Without real T3 SectioningAssignment.band data on this cohort there's still no dominant band to
    // match against, so this just proves the field round-trips and Mode 4 tolerates it cleanly; the full
    // band-mix-match scenario is exercised live against real SectioningAssignment data (see report).
    const patch = await request(app).patch('/api/users/me/band-affinity').set(authHeader(chemTeacher2Token))
      .send({ declaredBandAffinity: { support: 'STRONG', mid: 'MEDIUM', advanced: 'NONE' } })
    expect(patch.status).toBe(200)
    expect(patch.body.user.declaredBandAffinity.support).toBe('STRONG')

    const res = await request(app).post('/api/timetable/teaching-assignments/resolve').set(authHeader(fx.tokens.admin))
      .send({ teachingRequirementId: chemReqId, termId: fx.ids.termId })
    expect(res.status).toBe(200)
  })
})

describe('T5 — TeacherAvailability (T1-promised, T5-delivered)', () => {
  it('sets and reads back a teacher\'s availability', async () => {
    const put = await request(app).put('/api/timetable/teacher-availability').set(authHeader(fx.tokens.admin)).send({
      teacherId: chemTeacher1Id,
      entries: [{ dayOfWeek: 1, periodIdx: 5, status: 'NOT_PREFERRED' }, { dayOfWeek: 2, periodIdx: 0, status: 'PREFERRED' }],
    })
    expect(put.status).toBe(200)
    expect(put.body.items).toHaveLength(2)
    const get = await request(app).get(`/api/timetable/teacher-availability/${chemTeacher1Id}`).set(authHeader(fx.tokens.admin))
    expect(get.body.items).toHaveLength(2)
  })
})

describe('T5 §2/§3 — Preference + PreferenceProfile', () => {
  it('seeds both ASSIGNMENT and REFINEMENT preference defaults, idempotently', async () => {
    const res = await request(app).post('/api/timetable/preferences/seed-defaults').set(authHeader(fx.tokens.admin))
    expect(res.status).toBe(200)
    expect(res.body.added).toBeGreaterThan(0)
    const again = await request(app).post('/api/timetable/preferences/seed-defaults').set(authHeader(fx.tokens.admin))
    expect(again.body.added).toBe(0)
  })

  it('seeds all 7 named preference profiles as real usable weight sets', async () => {
    const res = await request(app).post('/api/timetable/preference-profiles/seed-defaults').set(authHeader(fx.tokens.admin))
    expect(res.status).toBe(200)
    expect(res.body.added).toBe(7)
    const list = await request(app).get('/api/timetable/preference-profiles').set(authHeader(fx.tokens.admin))
    const names = list.body.items.map((p: { name: string }) => p.name).sort()
    expect(names).toEqual(['BALANCED', 'DEFAULT', 'EXAM_PREP', 'LAB_HEAVY', 'PRIMARY_SCHOOL', 'STUDENT_FRIENDLY', 'TEACHER_FRIENDLY'])
    for (const p of list.body.items) if (p.name !== 'DEFAULT') expect(Object.keys(p.weightOverrides).length).toBeGreaterThan(0)
  })

  it('activates a profile, deactivating the previous one', async () => {
    const res = await request(app).post('/api/timetable/preference-profiles/activate').set(authHeader(fx.tokens.admin)).send({ name: 'LAB_HEAVY' })
    expect(res.status).toBe(200)
    expect(res.body.item.active).toBe(true)
    const list = await request(app).get('/api/timetable/preference-profiles').set(authHeader(fx.tokens.admin))
    expect(list.body.items.filter((p: { active: boolean }) => p.active)).toHaveLength(1)
    // reset to DEFAULT for the refinement tests below, which compare profile outputs explicitly
    await request(app).post('/api/timetable/preference-profiles/activate').set(authHeader(fx.tokens.admin)).send({ name: 'DEFAULT' })
  })

  it('teacher cannot seed or activate profiles; admin can', async () => {
    const res = await request(app).post('/api/timetable/preference-profiles/seed-defaults').set(authHeader(fx.tokens.teacher))
    expect(res.status).toBe(403)
  })
})

describe('T5 §2 — SA refinement: hard-safety, measurable improvement, incremental scoring', () => {
  // Deliberately over-constrained scenario: several sections sharing 2 teachers, forcing genuine lab
  // splits / same-day repeats in the greedy pass so refinement has real penalty to remove.
  let refineCohortIds: string[] = []
  let genTermId: string

  beforeAll(async () => {
    genTermId = fx.ids.termId
    const gradeId = fx.ids.gradeId
    const boardId = fx.ids.boardId
    const yearId = fx.ids.yearId
    const mathTeacher = fx.ids.teacherId

    const sectionIds: string[] = [fx.ids.classId]
    for (const section of ['R1', 'R2']) {
      const cls = await request(app).post('/api/academic/classes').set(authHeader(fx.tokens.superadmin))
        .send({ academicYearId: yearId, boardId, gradeId, section, capacity: 2 })
      sectionIds.push(cls.body.item.id)
      await request(app).post('/api/academic/class-subjects').set(authHeader(fx.tokens.superadmin))
        .send({ classId: cls.body.item.id, subjectId: fx.ids.subjectId, teacherId: mathTeacher, periodsPerWeek: 5 })
      await request(app).post('/api/academic/class-subjects').set(authHeader(fx.tokens.superadmin))
        .send({ classId: cls.body.item.id, subjectId: chemSubjectId, teacherId: chemTeacher1Id, periodsPerWeek: 4 })
    }

    const cohorts = await request(app).get('/api/academic/cohorts').query({ academicYearId: yearId }).set(authHeader(fx.tokens.admin))
    refineCohortIds = sectionIds.map(cid => cohorts.body.items.find((c: { autoGenerated: boolean; classIds: string[] }) => c.autoGenerated && c.classIds.includes(cid)).id)

    await request(app).post('/api/timetable/teaching-requirements/seed-from-class-subjects').set(authHeader(fx.tokens.admin)).send({ academicYearId: yearId })

    // Give the shared teachers some NOT_PREFERRED slots so UNPREFERRED_SLOT has real penalty to reduce.
    await request(app).put('/api/timetable/teacher-availability').set(authHeader(fx.tokens.admin)).send({
      teacherId: mathTeacher, entries: [{ dayOfWeek: 1, periodIdx: 0, status: 'NOT_PREFERRED' }, { dayOfWeek: 3, periodIdx: 0, status: 'NOT_PREFERRED' }],
    })
  })

  it('generates a draft, then refinement measurably improves total penalty with zero hard-constraint violations at every stage', async () => {
    const gen = await request(app).post('/api/timetable/auto-generate').set(authHeader(fx.tokens.admin)).send({
      cohortIds: refineCohortIds, termId: genTermId, mode: 'full-regenerate',
    })
    expect(gen.status).toBe(200)
    expect(gen.body.draftEntries.length).toBeGreaterThan(0)

    // Stage 1: greedy output itself must already be hard-clean (T4's own invariant, re-checked here).
    type Entry = { classId: string; dayOfWeek: number; periodIdx: number; teacherId?: string; roomId?: string }
    const violations = (entries: Entry[], key: (e: Entry) => string | undefined) => {
      const seen = new Map<string, number>()
      for (const e of entries) { const k = key(e); if (!k) continue; const slot = `${k}@${e.dayOfWeek}:${e.periodIdx}`; seen.set(slot, (seen.get(slot) ?? 0) + 1) }
      return [...seen.values()].filter(c => c > 1).length
    }
    expect(violations(gen.body.draftEntries, e => e.teacherId)).toBe(0)
    expect(violations(gen.body.draftEntries, e => e.roomId)).toBe(0)
    expect(violations(gen.body.draftEntries, e => e.classId)).toBe(0)

    const draftWithSubjectNames = gen.body.draftEntries.map((e: Entry & { subjectName: string; isDoublePeriod: boolean }) => ({ ...e }))

    // Stage 2: refine with a short but real time budget.
    const refine = await request(app).post('/api/timetable/auto-generate/refine').set(authHeader(fx.tokens.admin)).send({
      termId: genTermId, cohortIds: refineCohortIds, draftEntries: draftWithSubjectNames, timeBudgetMsPerGroup: 800,
    })
    expect(refine.status).toBe(200)
    expect(refine.body.hardViolationsBefore).toBe(0)
    expect(refine.body.hardViolationsAfter).toBe(0) // hard constraints never regress
    expect(refine.body.groups.length).toBeGreaterThan(0)
    for (const g of refine.body.groups) {
      expect(g.hardBefore).toBe(0)
      expect(g.hardAfter).toBe(0)
      expect(g.iterations).toBeGreaterThan(0)
    }
    // Measurable improvement (or at worst no regression — SA never accepts a worse "best").
    expect(refine.body.scoreAfter).toBeLessThanOrEqual(refine.body.scoreBefore)

    // Stage 3: re-check hard constraints on the REFINED entries via the same violations() logic — proves
    // "zero violations at every single stage", not just before/after.
    expect(violations(refine.body.draftEntries, (e: Entry) => e.teacherId)).toBe(0)
    expect(violations(refine.body.draftEntries, (e: Entry) => e.roomId)).toBe(0)
    expect(violations(refine.body.draftEntries, (e: Entry) => e.classId)).toBe(0)

    // Stage 4: commit the refined draft through the exact same commit path — proves refinement output is
    // still valid input to the existing, unchanged commit/validateGrid pipeline.
    const commit = await request(app).post('/api/timetable/auto-generate/commit').set(authHeader(fx.tokens.admin)).send({
      termId: genTermId, mode: 'full-regenerate', draftEntries: refine.body.draftEntries,
    })
    expect(commit.status).toBe(200)
  })

  it('two different PreferenceProfiles produce measurably different results on the same input', async () => {
    const gen = await request(app).post('/api/timetable/auto-generate').set(authHeader(fx.tokens.admin)).send({
      cohortIds: refineCohortIds, termId: genTermId, mode: 'full-regenerate',
    })
    const draft = gen.body.draftEntries

    const refineWith = (profile: string) => request(app).post('/api/timetable/auto-generate/refine').set(authHeader(fx.tokens.admin)).send({
      termId: genTermId, cohortIds: refineCohortIds, draftEntries: draft, timeBudgetMsPerGroup: 600, preferenceProfileName: profile, seed: 42,
    })

    const labHeavy = await refineWith('LAB_HEAVY')
    const studentFriendly = await refineWith('STUDENT_FRIENDLY')
    expect(labHeavy.status).toBe(200)
    expect(studentFriendly.status).toBe(200)

    // Different weight profiles must yield different score compositions (a LAB_HEAVY-weighted run should
    // score lab splits much more harshly than STUDENT_FRIENDLY's own detail breakdown for the same input).
    const labHeavyLabDetail = labHeavy.body.groups.reduce((a: number, g: { scoreBefore: { details: { labSplits: number } } }) => a + g.scoreBefore.details.labSplits, 0)
    const studentFriendlyLabDetail = studentFriendly.body.groups.reduce((a: number, g: { scoreBefore: { details: { labSplits: number } } }) => a + g.scoreBefore.details.labSplits, 0)
    // Same underlying draft -> same raw labSplits count before weighting (sanity: both measured the same input).
    expect(labHeavyLabDetail).toBe(studentFriendlyLabDetail)
    // But the WEIGHTED scoreBefore.major must differ since LAB_HEAVY weights LAB_SPLIT at 4x vs STUDENT_FRIENDLY's 1.5x.
    const labHeavyMajor = labHeavy.body.groups.reduce((a: number, g: { scoreBefore: { major: number } }) => a + g.scoreBefore.major, 0)
    const studentFriendlyMajor = studentFriendly.body.groups.reduce((a: number, g: { scoreBefore: { major: number } }) => a + g.scoreBefore.major, 0)
    if (labHeavyLabDetail > 0) expect(labHeavyMajor).toBeGreaterThan(studentFriendlyMajor)
  })

  it('a teacher shared ACROSS two different cohort-groups (different grades) never collides after refinement — the exact cross-group gap decompose-by-grade must guard against', async () => {
    // Real bug caught during this phase's own live verification: refining grade A and grade B as fully
    // independent SA passes (correct for scoring, per D2/T0) is NOT automatically safe for hard constraints
    // when a teacher genuinely teaches in both grades — grade A's SA has no visibility into grade B's own
    // placements and vice versa, so without explicit cross-group occupancy sharing, one group's move can
    // relocate a shared teacher straight into a slot the OTHER group already, validly occupies.
    const otherGrade = await request(app).post('/api/academic/grades').set(authHeader(fx.tokens.superadmin)).send({ label: 'IX-T5' })
    const otherGradeId = otherGrade.body.item.id
    const otherClass = await request(app).post('/api/academic/classes').set(authHeader(fx.tokens.superadmin))
      .send({ academicYearId: fx.ids.yearId, boardId: fx.ids.boardId, gradeId: otherGradeId, section: 'CROSS', capacity: 2 })
    // The SAME chemTeacher1 (already teaching Chemistry in the VIII-grade group) also teaches Chemistry
    // here, in a completely different grade — an entirely ordinary real-world scenario.
    await request(app).post('/api/academic/class-subjects').set(authHeader(fx.tokens.superadmin))
      .send({ classId: otherClass.body.item.id, subjectId: chemSubjectId, teacherId: chemTeacher1Id, periodsPerWeek: 4 })
    const cohorts = await request(app).get('/api/academic/cohorts').query({ academicYearId: fx.ids.yearId }).set(authHeader(fx.tokens.admin))
    const otherCohortId = cohorts.body.items.find((c: { autoGenerated: boolean; classIds: string[] }) => c.autoGenerated && c.classIds.includes(otherClass.body.item.id)).id
    await request(app).post('/api/timetable/teaching-requirements/seed-from-class-subjects').set(authHeader(fx.tokens.admin)).send({ academicYearId: fx.ids.yearId })

    const allCohortIds = [...refineCohortIds, otherCohortId]
    const gen = await request(app).post('/api/timetable/auto-generate').set(authHeader(fx.tokens.admin)).send({
      cohortIds: allCohortIds, termId: genTermId, mode: 'full-regenerate',
    })
    expect(gen.status).toBe(200)

    const refine = await request(app).post('/api/timetable/auto-generate/refine').set(authHeader(fx.tokens.admin)).send({
      termId: genTermId, cohortIds: allCohortIds, draftEntries: gen.body.draftEntries, timeBudgetMsPerGroup: 1500, seed: 7,
    })
    expect(refine.status).toBe(200)
    // Must be at least 2 distinct cohort-groups (VIII-grade + the new IX-T5 grade) — otherwise this test
    // isn't actually exercising cross-group decomposition at all.
    expect(refine.body.groups.length).toBeGreaterThanOrEqual(2)
    expect(refine.body.hardViolationsAfter).toBe(0)

    // Re-verify by hand on the merged output, independent of the endpoint's own reported number.
    type Entry = { teacherId?: string; roomId?: string; classId: string; dayOfWeek: number; periodIdx: number }
    const violations = (entries: Entry[], key: (e: Entry) => string | undefined) => {
      const seen = new Map<string, number>()
      for (const e of entries) { const k = key(e); if (!k) continue; const slot = `${k}@${e.dayOfWeek}:${e.periodIdx}`; seen.set(slot, (seen.get(slot) ?? 0) + 1) }
      return [...seen.values()].filter(c => c > 1).length
    }
    expect(violations(refine.body.draftEntries, e => e.teacherId)).toBe(0)
    expect(violations(refine.body.draftEntries, e => e.roomId)).toBe(0)
    expect(violations(refine.body.draftEntries, e => e.classId)).toBe(0)
  })
})

describe('T5 regression — T4 FIXED mode still works unchanged', () => {
  it('FIXED-mode requirement with an existing assignment is untouched by generation', async () => {
    const reqs = await request(app).get('/api/timetable/teaching-requirements').query({ cohortId: cohortAId }).set(authHeader(fx.tokens.admin))
    const math = reqs.body.items.find((r: { id: string }) => r.id === mathReqId)
    expect(math.assignmentMode).toBe('FIXED')
    const assignments = await request(app).get('/api/timetable/teaching-assignments').query({ teachingRequirementId: mathReqId }).set(authHeader(fx.tokens.admin))
    expect(assignments.body.items[0].teacherId).toBe(fx.ids.teacherId)
  })
})

// Phase T10 §2 — Phase 26's legacy class-scoped Auto-Generate (classId, no cohortIds) is retired; the test
// that used to live here proving it "still works byte-identically" was removed along with the code path it
// exercised. See solverCore.test.ts's "T10 §2 regression" block for the replacement coverage confirming
// the classId shape is now rejected by validation instead of silently accepted.

void labRoomId
