import { describe, it, expect, beforeAll } from 'vitest'
import request from 'supertest'
import { createApp } from '../src/app'
import { buildFixture, type Fixture } from './helpers/fixtures'
import { authHeader } from './helpers/auth'

// Phase T1 — scheduling data-model foundations (phase-t1-timetable-foundations.md). buildFixture already
// creates one class (VIII-A via fx.ids.classId), so its auto-generated section Cohort is exercised for
// free by the very first test below.

const app = createApp()
let fx: Fixture

beforeAll(async () => {
  fx = await buildFixture(app)
})

describe('T1 §1 — Cohort: auto-generation on class create/update/delete', () => {
  it('creating a class auto-creates a 1:1 SECTION cohort pointing only at it', async () => {
    const res = await request(app).get('/api/academic/cohorts').query({ academicYearId: fx.ids.yearId }).set(authHeader(fx.tokens.admin))
    expect(res.status).toBe(200)
    const auto = res.body.items.find((c: { classIds: string[]; autoGenerated: boolean }) => c.autoGenerated && c.classIds.includes(fx.ids.classId))
    expect(auto).toBeTruthy()
    expect(auto.type).toBe('SECTION')
    expect(auto.classIds).toEqual([fx.ids.classId])
    expect(auto.name).toBe('VIII-A')
  })

  it('a second class gets its own distinct 1:1 cohort', async () => {
    const cls = await request(app).post('/api/academic/classes').set(authHeader(fx.tokens.superadmin))
      .send({ academicYearId: fx.ids.yearId, boardId: fx.ids.boardId, gradeId: fx.ids.gradeId, section: 'B', capacity: 2 })
    expect(cls.status).toBe(201)

    const res = await request(app).get('/api/academic/cohorts').query({ academicYearId: fx.ids.yearId }).set(authHeader(fx.tokens.admin))
    const auto = res.body.items.filter((c: { autoGenerated: boolean }) => c.autoGenerated)
    expect(auto).toHaveLength(2)
    const forB = auto.find((c: { classIds: string[] }) => c.classIds.includes(cls.body.item.id))
    expect(forB.name).toBe('VIII-B')
  })

  it('renaming a class section keeps its auto cohort in sync', async () => {
    const cls = await request(app).post('/api/academic/classes').set(authHeader(fx.tokens.superadmin))
      .send({ academicYearId: fx.ids.yearId, boardId: fx.ids.boardId, gradeId: fx.ids.gradeId, section: 'C', capacity: 2 })
    await request(app).patch(`/api/academic/classes/${cls.body.item.id}`).set(authHeader(fx.tokens.superadmin)).send({ section: 'D' })

    const res = await request(app).get('/api/academic/cohorts').query({ academicYearId: fx.ids.yearId }).set(authHeader(fx.tokens.admin))
    const auto = res.body.items.find((c: { classIds: string[] }) => c.classIds.includes(cls.body.item.id))
    expect(auto.name).toBe('VIII-D')
  })

  it('deleting a class removes its now-orphaned auto cohort', async () => {
    const cls = await request(app).post('/api/academic/classes').set(authHeader(fx.tokens.superadmin))
      .send({ academicYearId: fx.ids.yearId, boardId: fx.ids.boardId, gradeId: fx.ids.gradeId, section: 'E', capacity: 2 })
    const del = await request(app).delete(`/api/academic/classes/${cls.body.item.id}`).set(authHeader(fx.tokens.superadmin))
    expect(del.status).toBe(200)

    const res = await request(app).get('/api/academic/cohorts').query({ academicYearId: fx.ids.yearId }).set(authHeader(fx.tokens.admin))
    expect(res.body.items.some((c: { classIds: string[] }) => c.classIds.includes(cls.body.item.id))).toBe(false)
  })

  it('the auto-generated cohort cannot be deleted or have its membership edited directly', async () => {
    const list = await request(app).get('/api/academic/cohorts').query({ academicYearId: fx.ids.yearId }).set(authHeader(fx.tokens.admin))
    const auto = list.body.items.find((c: { classIds: string[]; autoGenerated: boolean }) => c.autoGenerated && c.classIds.includes(fx.ids.classId))

    const del = await request(app).delete(`/api/academic/cohorts/${auto.id}`).set(authHeader(fx.tokens.superadmin))
    expect(del.status).toBe(400)

    const patch = await request(app).patch(`/api/academic/cohorts/${auto.id}`).set(authHeader(fx.tokens.superadmin)).send({ classIds: [fx.ids.classId] })
    expect(patch.status).toBe(400)
  })
})

describe('T1 §1 — Cohort: manual cross-section cohorts', () => {
  let secondClassId: string

  beforeAll(async () => {
    const cls = await request(app).post('/api/academic/classes').set(authHeader(fx.tokens.superadmin))
      .send({ academicYearId: fx.ids.yearId, boardId: fx.ids.boardId, gradeId: fx.ids.gradeId, section: 'F', capacity: 2 })
    secondClassId = cls.body.item.id
  })

  it('creates a cross-section cohort spanning two classes of the same academic year', async () => {
    const res = await request(app).post('/api/academic/cohorts').set(authHeader(fx.tokens.superadmin)).send({
      name: 'VIII-ALL', academicYearId: fx.ids.yearId, gradeId: fx.ids.gradeId, type: 'GRADE',
      classIds: [fx.ids.classId, secondClassId],
    })
    expect(res.status).toBe(201)
    expect(res.body.item.classIds.sort()).toEqual([fx.ids.classId, secondClassId].sort())
    expect(res.body.item.autoGenerated).toBe(false)
  })

  it('rejects mixing classes from two different academic years', async () => {
    const otherYear = await request(app).post('/api/academic/years').set(authHeader(fx.tokens.superadmin))
      .send({ label: '2027-28', startDate: '2027-06-01', endDate: '2028-05-31' })
    const otherClass = await request(app).post('/api/academic/classes').set(authHeader(fx.tokens.superadmin))
      .send({ academicYearId: otherYear.body.item.id, boardId: fx.ids.boardId, gradeId: fx.ids.gradeId, section: 'A', capacity: 2 })

    const res = await request(app).post('/api/academic/cohorts').set(authHeader(fx.tokens.superadmin)).send({
      name: 'Cross-year (invalid)', academicYearId: fx.ids.yearId, type: 'GRADE',
      classIds: [fx.ids.classId, otherClass.body.item.id],
    })
    expect(res.status).toBe(400)
  })

  it('teacher/student/parent/staff cannot create a manual cohort; admin can', async () => {
    for (const role of ['teacher', 'student', 'parent', 'staff'] as const) {
      const res = await request(app).post('/api/academic/cohorts').set(authHeader(fx.tokens[role]))
        .send({ name: 'nope', academicYearId: fx.ids.yearId, type: 'GRADE', classIds: [fx.ids.classId] })
      expect(res.status).toBe(403)
    }
  })
})

describe('T1 §2 — Room capabilities', () => {
  it('seeds the default capability catalog', async () => {
    const res = await request(app).post('/api/academic/capabilities/seed-defaults').set(authHeader(fx.tokens.admin))
    expect(res.status).toBe(200)
    expect(res.body.added).toBeGreaterThan(0)
    // Re-seeding is a no-op.
    const again = await request(app).post('/api/academic/capabilities/seed-defaults').set(authHeader(fx.tokens.admin))
    expect(again.body.added).toBe(0)
  })

  it('assigns capabilities to a room via the dedicated set-replace endpoint', async () => {
    const caps = await request(app).get('/api/academic/capabilities').set(authHeader(fx.tokens.admin))
    const ids = caps.body.items.slice(0, 2).map((c: { id: string }) => c.id)

    const res = await request(app).put(`/api/academic/rooms/${fx.ids.roomId}/capabilities`).set(authHeader(fx.tokens.admin))
      .send({ capabilityIds: ids })
    expect(res.status).toBe(200)
    expect(res.body.item.capabilityIds.sort()).toEqual(ids.sort())

    const rooms = await request(app).get('/api/academic/rooms').set(authHeader(fx.tokens.admin))
    const room = rooms.body.items.find((r: { id: string }) => r.id === fx.ids.roomId)
    expect(room.capabilityIds.sort()).toEqual(ids.sort())
  })

  it('rejects an unknown capability id', async () => {
    const res = await request(app).put(`/api/academic/rooms/${fx.ids.roomId}/capabilities`).set(authHeader(fx.tokens.admin))
      .send({ capabilityIds: ['does-not-exist'] })
    expect(res.status).toBe(404)
  })
})

describe('T1 §3 — TeacherQualification', () => {
  it('creates a qualification for the fixture teacher', async () => {
    const res = await request(app).post('/api/academic/teacher-qualifications').set(authHeader(fx.tokens.admin)).send({
      teacherId: fx.ids.teacherId, subjectId: fx.ids.subjectId, gradeRangeMin: 6, gradeRangeMax: 10, proficiency: 'PRIMARY', isPrimarySubject: true,
    })
    expect(res.status).toBe(201)
    expect(res.body.item.gradeRangeMin).toBe(6)
  })

  it('rejects gradeRangeMin > gradeRangeMax', async () => {
    const res = await request(app).post('/api/academic/teacher-qualifications').set(authHeader(fx.tokens.admin)).send({
      teacherId: fx.ids.teacherId, subjectId: fx.ids.subjectId, gradeRangeMin: 10, gradeRangeMax: 6, proficiency: 'PRIMARY',
    })
    expect(res.status).toBe(400)
  })

  it('rejects a non-teacher teacherId', async () => {
    const res = await request(app).post('/api/academic/teacher-qualifications').set(authHeader(fx.tokens.admin)).send({
      teacherId: fx.ids.staffId, subjectId: fx.ids.subjectId, gradeRangeMin: 6, gradeRangeMax: 10, proficiency: 'PRIMARY',
    })
    expect(res.status).toBe(400)
  })

  it('?teacherId= filters the list', async () => {
    const res = await request(app).get('/api/academic/teacher-qualifications').query({ teacherId: fx.ids.teacherId }).set(authHeader(fx.tokens.admin))
    expect(res.status).toBe(200)
    expect(res.body.items.every((q: { teacherId: string }) => q.teacherId === fx.ids.teacherId)).toBe(true)
  })
})

describe('T1 §4 — teacher band affinity self-service', () => {
  it('a teacher can declare their own band affinity', async () => {
    const res = await request(app).patch('/api/users/me/band-affinity').set(authHeader(fx.tokens.teacher)).send({
      declaredBandAffinity: { support: 'STRONG', mid: 'MEDIUM', advanced: 'NONE' },
    })
    expect(res.status).toBe(200)
    expect(res.body.user.declaredBandAffinity).toEqual({ support: 'STRONG', mid: 'MEDIUM', advanced: 'NONE' })
    expect(res.body.user.affinitySource).toBe('DECLARED')
    expect(res.body.user.verifiedBandAffinity).toBeUndefined()
  })

  it('non-teacher roles cannot use the endpoint', async () => {
    for (const role of ['student', 'parent', 'staff', 'admin'] as const) {
      const res = await request(app).patch('/api/users/me/band-affinity').set(authHeader(fx.tokens[role])).send({
        declaredBandAffinity: { support: 'STRONG', mid: 'MEDIUM', advanced: 'NONE' },
      })
      expect(res.status).toBe(403)
    }
  })

  it('rejects an invalid band level', async () => {
    const res = await request(app).patch('/api/users/me/band-affinity').set(authHeader(fx.tokens.teacher)).send({
      declaredBandAffinity: { support: 'VERY_STRONG', mid: 'MEDIUM', advanced: 'NONE' },
    })
    expect(res.status).toBe(400)
  })
})

describe('T1 §5 — WorkingDayPattern + day-scoped PeriodTemplate overrides', () => {
  it('creates a working-day pattern for the fixture year, and rejects a duplicate', async () => {
    const res = await request(app).post('/api/timetable/working-day-patterns').set(authHeader(fx.tokens.admin)).send({
      academicYearId: fx.ids.yearId, workingDays: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'], saturdayPattern: 'ALTERNATE_1_3',
    })
    expect(res.status).toBe(201)

    const dup = await request(app).post('/api/timetable/working-day-patterns').set(authHeader(fx.tokens.admin)).send({
      academicYearId: fx.ids.yearId, workingDays: ['Mon'], saturdayPattern: 'NONE',
    })
    expect(dup.status).toBe(409)
  })

  it('base period-template listing is unaffected by this phase (byte-identical shape)', async () => {
    const base = await request(app).post('/api/timetable/period-templates').set(authHeader(fx.tokens.superadmin)).send({
      name: 'Weekday standard',
      periods: [{ idx: 0, label: 'P1', start: '09:00', end: '09:45', kind: 'class' }],
    })
    expect(base.status).toBe(201)
    expect(Object.keys(base.body.item).sort()).toEqual(['id', 'isDefault', 'name', 'periods'].sort())

    const list = await request(app).get('/api/timetable/period-templates').set(authHeader(fx.tokens.superadmin))
    // Only base templates (dayOfWeek null) appear here — overrides created below must never leak in.
    expect(list.body.items.every((t: Record<string, unknown>) => Object.keys(t).sort().join(',') === ['id', 'isDefault', 'name', 'periods'].sort().join(','))).toBe(true)
  })

  it('adds a Saturday override to the base template and resolves it correctly', async () => {
    const base = await request(app).post('/api/timetable/period-templates').set(authHeader(fx.tokens.superadmin)).send({
      name: 'Base for overrides',
      periods: [{ idx: 0, label: 'P1', start: '09:00', end: '09:45', kind: 'class' }],
    })
    const baseId = base.body.item.id

    const override = await request(app).post('/api/timetable/period-templates/overrides').set(authHeader(fx.tokens.superadmin)).send({
      baseTemplateId: baseId, dayOfWeek: 6, name: 'Saturday half-day',
      periods: [{ idx: 0, label: 'P1', start: '09:00', end: '11:00', kind: 'class' }],
    })
    expect(override.status).toBe(201)

    const resolveSat = await request(app).get(`/api/timetable/period-templates/${baseId}/resolve`).query({ dayOfWeek: 6 }).set(authHeader(fx.tokens.superadmin))
    expect(resolveSat.body.item.dayOfWeek).toBe(6)
    expect(resolveSat.body.item.periods[0].end).toBe('11:00')

    const resolveMon = await request(app).get(`/api/timetable/period-templates/${baseId}/resolve`).query({ dayOfWeek: 1 }).set(authHeader(fx.tokens.superadmin))
    expect(resolveMon.body.item.dayOfWeek).toBeNull()
    expect(resolveMon.body.item.periods[0].end).toBe('09:45')

    // A duplicate override for the same day is rejected.
    const dup = await request(app).post('/api/timetable/period-templates/overrides').set(authHeader(fx.tokens.superadmin)).send({
      baseTemplateId: baseId, dayOfWeek: 6, name: 'Duplicate Saturday',
      periods: [{ idx: 0, label: 'P1', start: '09:00', end: '10:00', kind: 'class' }],
    })
    expect(dup.status).toBe(409)
  })
})
