// Seeds the entire Advanced Timetable Generation domain (T1-T10) on top of seed/core.ts's Class/User/
// Subject/Room rows: cohorts, room capabilities, teacher qualifications/availability, working-day pattern
// + period template, teaching requirements/assignments, constraints, preference weights/profiles, two
// PUBLISHED TimetableVersions (+ one ARCHIVED predecessor) with real conflict-free TimetableEntry rows, a
// completed generation job, a lock, an elective block, and one substitution-workflow example (policy,
// accepted request, period hold, one-off Substitution row). See .agents/edunova/static-demo-plan.md and
// .agents/edunova/advanced-timetable-roadmap.md for the domain this covers.
//
// SIMULATED FOR SPEED: entries below come from timetableEngine.ts's deterministic greedy round-robin
// placer (real teacher/room/class conflict-checking, no soft-constraint optimization) — not a port of the
// real backtracking+simulated-annealing solver. See that file's own doc comment for the full rationale.

import type { Collections, Row } from '../store'
import { SCHOOL_ID } from '../store'
import { addSeedFragment } from './index'
import {
  PERIOD_TEMPLATE_ID, defaultPeriods, greedyPlace, labRoomIds, ensureClassSubject,
  type Occupancy, type PlacementRequest, type PlacedEntry,
} from '../modules/timetableEngine'

const CLASSES = ['class-9a', 'class-9b', 'class-10a', 'class-10b'] as const
const GRADE_OF: Record<string, string> = { 'class-9a': 'grade-9', 'class-9b': 'grade-9', 'class-10a': 'grade-10', 'class-10b': 'grade-10' }
const LABEL_OF: Record<string, string> = { 'class-9a': 'IX-A', 'class-9b': 'IX-B', 'class-10a': 'X-A', 'class-10b': 'X-B' }

/** ISO-ish weekday (1=Mon..5=Fri) -> a concrete date in the week containing today's anchor (2026-09-14, a
 * Monday), so seeded substitution/date examples are internally consistent without depending on real time. */
function dateForWeekday(dayOfWeek: number): string {
  const monday = new Date(Date.UTC(2026, 8, 14))
  const d = new Date(monday)
  d.setUTCDate(monday.getUTCDate() + (dayOfWeek - 1))
  return d.toISOString().slice(0, 10)
}

function seedTimetable(db: Collections) {
  // ───────────────────────── T1 — Cohorts, capabilities, qualifications, availability, working days ─────────────────────────

  db.Cohort = CLASSES.map(classId => ({
    id: `cohort-${classId.replace('class-', '')}`, schoolId: SCHOOL_ID, academicYearId: 'ay-2025',
    name: LABEL_OF[classId], gradeId: GRADE_OF[classId], type: 'SECTION', autoGenerated: true, classIds: [classId],
  } as Row))

  db.Capability = [
    { id: 'cap-projector', schoolId: SCHOOL_ID, name: 'Projector', code: 'PROJ' },
    { id: 'cap-smartboard', schoolId: SCHOOL_ID, name: 'Smart Board', code: 'SMART' },
    { id: 'cap-sciencelab', schoolId: SCHOOL_ID, name: 'Science Lab Equipment', code: 'SCILAB' },
    { id: 'cap-computerlab', schoolId: SCHOOL_ID, name: 'Computer Lab Equipment', code: 'COMPLAB' },
  ].map(r => r as Row)

  const quals: Array<[string, string, number, number, 'PRIMARY' | 'SECONDARY', boolean]> = [
    ['u-t', 'math', 9, 12, 'PRIMARY', true],
    ['u-t2', 'english', 9, 12, 'PRIMARY', true],
    ['u-t2', 'hindi', 9, 12, 'SECONDARY', false],
    ['u-t3', 'science', 9, 9, 'PRIMARY', true],
    ['u-t3', 'biology', 9, 12, 'SECONDARY', true],
    ['u-t4', 'physics', 9, 12, 'PRIMARY', true],
    ['u-t5', 'chemistry', 9, 12, 'PRIMARY', true],
    ['u-t6', 'computer', 9, 12, 'PRIMARY', true],
  ]
  db.TeacherQualification = quals.map(([teacherId, subjectId, gradeRangeMin, gradeRangeMax, proficiency, isPrimarySubject]) => ({
    id: `tq-${teacherId}-${subjectId}`, schoolId: SCHOOL_ID, teacherId, subjectId, gradeRangeMin, gradeRangeMax, proficiency, isPrimarySubject,
  } as Row))

  db.TeacherAvailability = [
    { id: 'ta-1', schoolId: SCHOOL_ID, teacherId: 'u-t4', dayOfWeek: 1, periodIdx: 1, status: 'UNAVAILABLE' },
    { id: 'ta-2', schoolId: SCHOOL_ID, teacherId: 'u-t', dayOfWeek: 5, periodIdx: 9, status: 'PREFERRED' },
    { id: 'ta-3', schoolId: SCHOOL_ID, teacherId: 'u-t2', dayOfWeek: 3, periodIdx: 1, status: 'NOT_PREFERRED' },
  ].map(r => r as Row)

  db.WorkingDayPattern = [
    { id: 'wdp-1', schoolId: SCHOOL_ID, academicYearId: 'ay-2025', workingDays: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'], saturdayPattern: 'NONE' } as Row,
  ]

  db.PeriodTemplate = [
    { id: PERIOD_TEMPLATE_ID, schoolId: SCHOOL_ID, name: 'Standard Day', isDefault: true, periods: defaultPeriods() } as Row,
  ]

  // ───────────────────────── T4/T5 — TeachingRequirement + TeachingAssignment ─────────────────────────
  // Deliberately broader than seed/core.ts's own (partial) ClassSubject rows — a real school schedules every
  // subject, not just the handful the foundation seed happened to wire up. `pe` is left intentionally
  // unassigned (no TeachingAssignment) on every cohort so the auto-generate/diagnostics UI has a real,
  // honest unplaced/diagnostic example to show, not just a happy path.
  interface ReqDef { subjectId: string; subjectName: string; teacherId: string | null; periodsPerWeek: number; duration: PlacementRequest['sessionDuration']; roomId: string | null; wantsLab: boolean }
  const reqDefsFor = (classId: string): ReqDef[] => {
    const common: ReqDef[] = [
      { subjectId: 'math', subjectName: 'Mathematics', teacherId: 'u-t', periodsPerWeek: 6, duration: 'SINGLE', roomId: null, wantsLab: false },
      { subjectId: 'english', subjectName: 'English', teacherId: 'u-t2', periodsPerWeek: 5, duration: 'SINGLE', roomId: null, wantsLab: false },
      { subjectId: 'computer', subjectName: 'Computer Science', teacherId: 'u-t6', periodsPerWeek: 4, duration: 'DOUBLE', roomId: 'room-b102', wantsLab: true },
      { subjectId: 'pe', subjectName: 'Physical Education', teacherId: null, periodsPerWeek: 3, duration: 'SINGLE', roomId: null, wantsLab: false },
    ]
    if (classId.startsWith('class-9')) {
      return [
        common[0], common[1],
        { subjectId: 'science', subjectName: 'Science', teacherId: 'u-t3', periodsPerWeek: 6, duration: 'SINGLE', roomId: null, wantsLab: true },
        { subjectId: 'hindi', subjectName: 'Hindi', teacherId: 'u-t2', periodsPerWeek: 4, duration: 'SINGLE', roomId: null, wantsLab: false },
        common[2], common[3],
      ]
    }
    return [
      common[0], common[1],
      { subjectId: 'physics', subjectName: 'Physics', teacherId: 'u-t4', periodsPerWeek: 5, duration: 'SINGLE', roomId: null, wantsLab: true },
      { subjectId: 'chemistry', subjectName: 'Chemistry', teacherId: 'u-t5', periodsPerWeek: 5, duration: 'SINGLE', roomId: null, wantsLab: true },
      common[2], common[3],
    ]
  }

  const teachingRequirements: Row[] = []
  const teachingAssignments: Row[] = []
  const placementRequests: PlacementRequest[] = []
  const teacherNameOf = (id: string | null) => (db.User ?? []).find(u => u.id === id)?.name as string | undefined ?? null

  for (const classId of CLASSES) {
    const cohortId = `cohort-${classId.replace('class-', '')}`
    for (const def of reqDefsFor(classId)) {
      const reqId = `trq-${classId.replace('class-', '')}-${def.subjectId}`
      teachingRequirements.push({
        id: reqId, schoolId: SCHOOL_ID, cohortId, subjectId: def.subjectId,
        requiredPeriodsPerWeek: def.periodsPerWeek, sessionDuration: def.duration,
        roomRequirement: def.roomId ? 'SPECIFIC_ROOM' : def.wantsLab ? 'LAB_TYPE' : 'ANY',
        specificRoomId: def.roomId, labDoubleAllowed: def.duration === 'DOUBLE', assignmentMode: 'FIXED',
      } as Row)
      if (def.teacherId) {
        teachingAssignments.push({
          id: `tas-${classId.replace('class-', '')}-${def.subjectId}`, schoolId: SCHOOL_ID, teachingRequirementId: reqId,
          teacherId: def.teacherId, assignmentMode: 'FIXED', selectionReason: 'Seeded fixed assignment matching the school\'s existing subject-teacher pairing',
          createdAt: '2025-04-01T00:00:00.000Z', createdBy: 'u-ad',
        } as Row)
        placementRequests.push({
          classId, subjectId: def.subjectId, subjectName: def.subjectName, teacherId: def.teacherId, teacherName: teacherNameOf(def.teacherId),
          periodsPerWeek: def.periodsPerWeek, sessionDuration: def.duration, roomId: def.roomId, wantsLab: def.wantsLab,
        })
      }
    }
  }
  db.TeachingRequirement = teachingRequirements
  db.TeachingAssignment = teachingAssignments

  // ───────────────────────── T4 §3 — Constraint Builder defaults ─────────────────────────
  const constraintTypes = ['TEACHER_COLLISION', 'ROOM_COLLISION', 'COHORT_COLLISION', 'TEACHER_AVAILABILITY', 'ROOM_CAPABILITY_MATCH', 'REQUIRED_WEEKLY_PERIODS', 'FIXED_SESSION']
  db.Constraint = constraintTypes.map(type => ({
    id: `constraint-${type.toLowerCase()}`, schoolId: SCHOOL_ID, type, scope: 'SCHOOL', scopeId: null,
    severity: 'HARD', enabled: true, parameters: {}, source: 'SYSTEM',
  } as Row))

  // ───────────────────────── T5 §2/§3 — Preference weights + PreferenceProfile ─────────────────────────
  const assignmentWeights: Record<string, number> = { QUALIFICATION_MATCH: 30, AVAILABILITY_MATCH: 15, WORKLOAD_BALANCE: 20, CLASS_SUITABILITY: 10, TEACHER_PREFERENCE: 10, CONFLICT_MINIMIZATION: 10, BAND_AFFINITY: 5 }
  const refinementWeights: Record<string, number> = { LAB_SPLIT: 25, TEACHER_DAILY_OVERLOAD: 20, TEACHER_WEEKLY_OVERLOAD: 15, WORKLOAD_VARIANCE: 15, TEACHER_GAPS: 10, UNPREFERRED_SLOT: 10, FORCED_SAME_DAY_REPEAT: 3, ADJACENT_SAME_SUBJECT: 2 }
  const substitutionWeights: Record<string, number> = { QUALIFICATION_MATCH: 40, SAME_SUBJECT: 20, AVAILABILITY_FIT: 15, WORKLOAD_HEADROOM: 10, AVOIDS_CONSECUTIVE_LOAD: 5, PREFERENCE: 5, CLASS_SUITABILITY: 5 }
  const prefRows: Row[] = []
  let priority = 0
  for (const [scope, weights] of [['ASSIGNMENT', assignmentWeights], ['REFINEMENT', refinementWeights], ['SUBSTITUTION', substitutionWeights]] as const) {
    for (const [type, weight] of Object.entries(weights)) {
      prefRows.push({ id: `pref-${scope.toLowerCase()}-${type.toLowerCase()}`, schoolId: SCHOOL_ID, type, scope, weight, priority: priority++, enabled: true, parameters: {} } as Row)
    }
  }
  db.Preference = prefRows

  db.PreferenceProfile = [
    { id: 'profile-default', schoolId: SCHOOL_ID, name: 'DEFAULT', description: 'The school\'s standard, unmodified weight table.', weightOverrides: {}, active: true },
    { id: 'profile-balanced', schoolId: SCHOOL_ID, name: 'BALANCED', description: 'An even hand across every soft constraint.', weightOverrides: {}, active: false },
    { id: 'profile-teacher-friendly', schoolId: SCHOOL_ID, name: 'TEACHER_FRIENDLY', description: 'Minimizes teacher gaps and daily overload.', weightOverrides: { TEACHER_GAPS: 30, TEACHER_DAILY_OVERLOAD: 35 }, active: false },
    { id: 'profile-student-friendly', schoolId: SCHOOL_ID, name: 'STUDENT_FRIENDLY', description: 'Modestly discourages split lab sessions.', weightOverrides: { LAB_SPLIT: 37.5 }, active: false },
    { id: 'profile-exam-prep', schoolId: SCHOOL_ID, name: 'EXAM_PREP', description: 'Prioritizes even workload distribution ahead of exams.', weightOverrides: { WORKLOAD_VARIANCE: 30 }, active: false },
    { id: 'profile-primary-school', schoolId: SCHOOL_ID, name: 'PRIMARY_SCHOOL', description: 'Leans harder against unpreferred slots for younger classes.', weightOverrides: { UNPREFERRED_SLOT: 20 }, active: false },
    { id: 'profile-lab-heavy', schoolId: SCHOOL_ID, name: 'LAB_HEAVY', description: 'Strongly penalizes split lab sessions (4x the default weight).', weightOverrides: { LAB_SPLIT: 100 }, active: false },
  ].map(r => r as Row)

  // ───────────────────────── Generation: one deterministic greedy pass, reused for both terms ─────────────────────────
  const classBusy: Occupancy = new Map(); const teacherBusy: Occupancy = new Map(); const roomBusy: Occupancy = new Map()
  const { placed, unplaced } = greedyPlace(db, placementRequests, classBusy, teacherBusy, roomBusy, labRoomIds(db))

  // A real demonstration SharedSession: IX-A and IX-B's Computer period, taught together by u-t6 in the
  // same lab room at the same slot (T6 §1 — 2+ TimetableEntry rows tagged with the same sessionId are never
  // a collision). Finds the first slot free for both classes + the teacher + the room using the SAME
  // occupancy maps the generation pass above already populated, so it's guaranteed conflict-free.
  const WORKING_DAYS = [1, 2, 3, 4, 5]
  const CLASS_IDXS = [1, 2, 3, 5, 6, 7, 9, 10]
  let sharedSlot: { day: number; idx: number } | null = null
  outer: for (const day of WORKING_DAYS) {
    for (const idx of CLASS_IDXS) {
      const slot = `${day}:${idx}`
      const free = !(classBusy.get('class-9a')?.has(slot)) && !(classBusy.get('class-9b')?.has(slot)) &&
        !(teacherBusy.get('u-t6')?.has(slot)) && !(roomBusy.get('room-b102')?.has(slot))
      if (free) { sharedSlot = { day, idx }; break outer }
    }
  }
  const sharedEntries: PlacedEntry[] = []
  let sharedSession: Row | undefined
  if (sharedSlot) {
    const cs9a = ensureClassSubject(db, 'class-9a', 'computer', 'u-t6', 1)
    const cs9b = ensureClassSubject(db, 'class-9b', 'computer', 'u-t6', 1)
    sharedSession = {
      id: 'sess-shared-9-computer', schoolId: SCHOOL_ID, termId: 't3', subjectId: 'computer',
      teachingAssignmentId: 'tas-9a-computer', teacherId: 'u-t6', roomId: 'room-b102', sessionType: 'SHARED',
      durationPeriods: 1, isSplittable: false, jobId: undefined, committed: true, committedAt: '2026-09-01T00:00:00.000Z',
      createdAt: '2026-09-01T00:00:00.000Z', entries: [{ dayOfWeek: sharedSlot.day, periodIdx: sharedSlot.idx }],
      cohortIds: ['cohort-9a', 'cohort-9b'], requirementIds: ['trq-9a-computer', 'trq-9b-computer'], isShared: true,
    } as Row
    sharedEntries.push(
      { classId: 'class-9a', dayOfWeek: sharedSlot.day, periodIdx: sharedSlot.idx, classSubjectId: cs9a.id, roomId: 'room-b102', teacherId: 'u-t6', sessionId: 'sess-shared-9-computer' },
      { classId: 'class-9b', dayOfWeek: sharedSlot.day, periodIdx: sharedSlot.idx, classSubjectId: cs9b.id, roomId: 'room-b102', teacherId: 'u-t6', sessionId: 'sess-shared-9-computer' },
    )
  }
  db.TimetableSession = sharedSession ? [sharedSession] : []

  const fullEntries = [...placed, ...sharedEntries]
  const oldEntries = placed.filter(e => e.classId === 'class-9a' || e.classId === 'class-9b')

  // ───────────────────────── T7 — TimetableVersions (2 PUBLISHED + 1 ARCHIVED predecessor) ─────────────────────────
  db.TimetableVersion = [
    {
      id: 'tv-t3-old', schoolId: SCHOOL_ID, academicYearId: 'ay-2025', termId: 't3',
      scopeCohortIds: ['cohort-9a', 'cohort-9b'], scopeClassIds: ['class-9a', 'class-9b'],
      status: 'ARCHIVED', parentVersionId: undefined, generationJobId: undefined, changeReason: 'Initial generation — grade IX only',
      entries: oldEntries, diffFromParent: { added: oldEntries, removed: [], changed: [] },
      publishedAt: '2026-08-20T08:00:00.000Z', archivedAt: '2026-09-01T08:00:00.000Z',
      createdById: 'u-ad', createdAt: '2026-08-19T08:00:00.000Z',
    },
    {
      id: 'tv-t3-current', schoolId: SCHOOL_ID, academicYearId: 'ay-2025', termId: 't3',
      scopeCohortIds: ['cohort-9a', 'cohort-9b', 'cohort-10a', 'cohort-10b'], scopeClassIds: [...CLASSES],
      status: 'PUBLISHED', parentVersionId: 'tv-t3-old', generationJobId: 'gj-1', changeReason: 'Full-school regeneration — grade X added',
      entries: fullEntries, diffFromParent: { added: fullEntries.filter(e => e.classId === 'class-10a' || e.classId === 'class-10b' || e.sessionId), removed: [], changed: [] },
      publishedAt: '2026-09-01T09:00:00.000Z', archivedAt: undefined,
      createdById: 'u-ad', createdAt: '2026-09-01T08:30:00.000Z',
    },
    {
      id: 'tv-t2', schoolId: SCHOOL_ID, academicYearId: 'ay-2025', termId: 't2',
      scopeCohortIds: ['cohort-9a', 'cohort-9b', 'cohort-10a', 'cohort-10b'], scopeClassIds: [...CLASSES],
      status: 'PUBLISHED', parentVersionId: undefined, generationJobId: undefined, changeReason: 'Term 2 timetable',
      entries: fullEntries, diffFromParent: { added: fullEntries, removed: [], changed: [] },
      publishedAt: '2025-08-05T08:00:00.000Z', archivedAt: undefined,
      createdById: 'u-ad', createdAt: '2025-08-04T08:00:00.000Z',
    },
  ].map(r => ({ ...r, entryCount: (r.entries as unknown[]).length } as Row))

  db.TimetableEditEvent = []

  // Materialize the two PUBLISHED versions' entries into real TimetableEntry rows — the ONE thing every
  // existing consumer (Take Attendance, teacher/parent timetable views, etc.) actually reads.
  let entryCounter = 0
  const materialize = (termId: string, versionId: string, entries: PlacedEntry[]) => entries.map(e => ({
    id: `tte-${++entryCounter}`, schoolId: SCHOOL_ID, classId: e.classId, termId, dayOfWeek: e.dayOfWeek, periodIdx: e.periodIdx,
    classSubjectId: e.classSubjectId, roomId: e.roomId ?? undefined, teacherId: e.teacherId ?? undefined,
    sessionId: e.sessionId ?? undefined, timetableVersionId: versionId,
  } as Row))
  db.TimetableEntry = [...materialize('t3', 'tv-t3-current', fullEntries), ...materialize('t2', 'tv-t2', fullEntries)]

  // ───────────────────────── T7 §3 — one example lock ─────────────────────────
  db.TimetableLock = [
    {
      id: 'lock-1', schoolId: SCHOOL_ID, timetableVersionId: 'tv-t3-current', lockType: 'TEACHER', targetType: 'teacher',
      targetId: 'u-t', dayOfWeek: undefined, periodIdx: undefined, reason: 'Exam invigilation duty this cycle — do not reschedule',
      createdById: 'u-ad', createdAt: '2026-09-05T00:00:00.000Z', active: true, releasedAt: undefined, releasedById: undefined,
    } as Row,
  ]

  // ───────────────────────── T6 §3 — one completed generation job ─────────────────────────
  db.TimetableGenerationJob = [
    {
      id: 'gj-1', schoolId: SCHOOL_ID, academicYearId: 'ay-2025', termId: 't3', scopeCohortIds: ['cohort-9a', 'cohort-9b', 'cohort-10a', 'cohort-10b'],
      status: 'COMPLETED', progress: 100, currentStage: 'Done', startedAt: '2026-09-01T08:00:00.000Z', completedAt: '2026-09-01T08:00:04.000Z',
      solverVersion: 'mock-greedy@1', timeLimit: 5000, randomSeed: 1234,
      solverParameters: { timeBudgetMsPerGroup: 5000, preferenceProfileName: 'DEFAULT', mode: 'full-regenerate' },
      outputHash: 'mock-deterministic-hash-t3-v1',
      diagnostics: unplaced.map(u => ({
        type: 'REQUIREMENT_UNSATISFIED', cohortLabel: u.classLabel, subjectName: u.subjectName, teacherName: u.teacherName,
        unplacedPeriods: u.remaining, cause: 'NO_TEACHER_ASSIGNED', reason: u.reason,
        suggestedActions: ['Assign a qualified teacher to this requirement (Teaching Assignments)', 'Or lower the required weekly periods'],
      })),
      errorCode: undefined, errorDetails: undefined, createdById: 'u-ad', createdAt: '2026-09-01T08:00:00.000Z',
    } as Row,
  ]

  // ───────────────────────── T6 §1b — one elective block (demonstration only — offerings reference
  // synthetic requirement ids rather than real Cohort/TeachingRequirement/TeachingAssignment/Session rows,
  // a documented "simulate for speed" simplification since the elective's own choose/commit flow doesn't
  // need those to exist for the demo to work end to end). ─────────────────────────
  db.ElectiveBlock = [
    {
      id: 'eb-1', schoolId: SCHOOL_ID, termId: 't3', gradeId: 'grade-10', name: 'Grade X Enrichment Elective',
      dayOfWeek: 5, periodIdx: 9, durationPeriods: 1, createdAt: '2026-09-01T00:00:00.000Z',
      offerings: [
        { id: 'eo-1', electiveBlockId: 'eb-1', teachingRequirementId: 'trq-elective-computer', subjectId: 'computer', teacherId: 'u-t6', roomId: 'room-b102', capacity: 20, registered: 0, choices: [] },
        { id: 'eo-2', electiveBlockId: 'eb-1', teachingRequirementId: 'trq-elective-biology', subjectId: 'biology', teacherId: 'u-t3', roomId: 'room-b101', capacity: 20, registered: 0, choices: [] },
      ],
    } as Row,
  ]

  // ───────────────────────── T9 — Substitution workflow example ─────────────────────────
  db.SubstitutionPolicy = [
    { id: 'subpolicy-1', schoolId: SCHOOL_ID, mode: 'TEACHER_INITIATED', minNoticeHoursForSubstitution: 12, allowCrossSubject: true, maxWeeklySubstitutePeriods: 30, tentativeHoldExpiryMinutes: 240 } as Row,
  ]

  const rahulPhysics10a = fullEntries.find(e => e.classId === 'class-10a' && e.teacherId === 'u-t4')
  db.SubstitutionRequest = []
  db.PeriodHold = []
  db.Substitution = []
  if (rahulPhysics10a) {
    const date = dateForWeekday(rahulPhysics10a.dayOfWeek)
    const entryRow = db.TimetableEntry.find(e => e.classId === 'class-10a' && e.teacherId === 'u-t4' && e.dayOfWeek === rahulPhysics10a.dayOfWeek && e.periodIdx === rahulPhysics10a.periodIdx && e.termId === 't3')
    if (entryRow) {
      const period = { date, dayOfWeek: rahulPhysics10a.dayOfWeek, periodIdx: rahulPhysics10a.periodIdx, timetableEntryId: entryRow.id }
      db.SubstitutionRequest = [
        {
          id: 'sr-1', schoolId: SCHOOL_ID, leaveRequestId: 'leave-demo-1', originalTeacherId: 'u-t4', substituteTeacherId: 'u-t5',
          periods: [period], status: 'ACCEPTED', mode: 'TEACHER_INITIATED', score: 78.4, isOverride: false, overrideNote: undefined,
          sentById: 'u-t4', sentAt: '2026-09-10T09:00:00.000Z', decidedById: 'u-t5', acceptedAt: '2026-09-10T10:00:00.000Z',
          declinedAt: undefined, expiredAt: undefined, createdAt: '2026-09-10T09:00:00.000Z',
        } as Row,
      ]
      db.PeriodHold = [
        { id: 'ph-1', schoolId: SCHOOL_ID, teacherId: 'u-t5', date, dayOfWeek: rahulPhysics10a.dayOfWeek, periodIdx: rahulPhysics10a.periodIdx, termId: 't3', holdType: 'LOCKED', sourceSubstitutionRequestId: 'sr-1', expiresAt: undefined, releasedAt: undefined } as Row,
      ]
      db.Substitution = [
        { id: 'sub-1', schoolId: SCHOOL_ID, timetableEntryId: entryRow.id, date, substituteTeacherId: 'u-t5', reason: 'Substitution workflow — teacher on approved leave', createdAt: '2026-09-10T10:05:00.000Z' } as Row,
      ]
    }
  }
}

addSeedFragment(seedTimetable)
