// One-time backfill for Phase T1 (roadmap D2, phase-t1-timetable-foundations.md §1): every Class created
// before this phase shipped has no auto-generated 1:1 section Cohort yet. New classes get one going
// forward via modules/classes/service.ts#create (which calls ensureSectionCohort). Run once per
// environment after the migration lands:
//
//   cd server && npx tsx scripts/backfillCohorts.ts
//
// Idempotent — safe to re-run; ensureSectionCohort skips classes that already have their cohort.
import { prisma } from '../src/prisma'
import { ensureSectionCohort } from '../src/modules/cohorts/service'
import { classInclude } from '../src/modules/classes/service'

async function main() {
  const classes = await prisma.class.findMany({ include: classInclude, orderBy: { createdAt: 'asc' } })
  let created = 0
  let already = 0
  for (const cls of classes) {
    const existing = await prisma.cohortClass.findFirst({ where: { classId: cls.id, cohort: { autoGenerated: true, type: 'SECTION' } } })
    await ensureSectionCohort(cls)
    if (existing) already++
    else created++
  }
  console.log(`Backfill complete: ${classes.length} classes scanned, ${created} section cohorts created, ${already} already had one.`)
}

main()
  .catch(err => {
    console.error(err)
    process.exitCode = 1
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
