import { z } from 'zod'
import { idStr, dateStr } from '../../lib/validate'

export const entryInput = z.object({
  dayOfWeek: z.number().int().min(1).max(6),
  periodIdx: z.number().int().min(0),
  classSubjectId: idStr,
  roomId: idStr.nullable().optional(),
  teacherId: idStr.nullable().optional(),
  // Phase T6 — set only by session materialization (./sessions.ts#materializeSession), never by the manual
  // builder or the legacy draft-commit path. Lets validateGrid recognize 2+ rows produced by the SAME
  // SharedSession (same teacher/room/period, different classes) as intentional, not a collision.
  sessionId: idStr.nullable().optional(),
})

export const putEntries = z.object({
  classId: idStr,
  termId: idStr,
  entries: z.array(entryInput),
})

export const copyBody = z.object({
  fromClassId: idStr,
  fromTermId: idStr,
  toClassId: idStr,
  toTermId: idStr,
})

export const publishBody = z.object({
  classId: idStr,
  termId: idStr,
  published: z.boolean(),
})

export const gridQuery = z.object({ classId: idStr, termId: idStr })
export const termQuery = z.object({ termId: idStr })
export const meQuery = z.object({ termId: idStr, studentId: idStr.optional() })

// ───────────────────────────── Phase 26: auto-generate ─────────────────────────────

export const autoGenerateMode = z.enum(['fill-empty', 'full-regenerate'])

// classId omitted → generate for every class in the term's academic year. Phase T4 (phase-t4-solver-
// core.md §4) adds `cohortIds`: when given (non-empty), generation runs the new Cohort/TeachingRequirement/
// TeachingAssignment-scoped path (./solver.ts) instead of the legacy ClassSubject-scoped one — `classId`
// is ignored in that case. Omitting `cohortIds` (the default) keeps Phase 26's existing behavior byte-
// identical, so the currently-shipped "Auto-Generate" UI needs zero changes.
// Phase T10 §2 — `classId`-scoped (or fully-omitted, "every class in the year") generation was Phase 26's
// legacy ClassSubject-scoped generator, retired now that the Cohort/TeachingRequirement-scoped solver
// (T4+) covers the same ground (every class has an auto-generated 1:1 "section cohort" per D2, so "this
// class" and "all classes" are just "this class's cohort" / "every cohort" from the caller's side) plus
// soft-constraint refinement, diagnostics, and shared/elective sessions the legacy path never had.
// `cohortIds` is required going forward — see phase-t10-migration.md §2.
export const autoGenerateBody = z.object({
  cohortIds: z.array(idStr).min(1),
  termId: idStr,
  mode: autoGenerateMode,
})

// The commit endpoint re-validates everything (see service.ts#commitAutoGenerate), so the draft entry
// shape is entryInput plus the classId each draft row belongs to (a generate call can span many classes).
export const autoGenerateDraftEntry = entryInput.extend({ classId: idStr })

export const autoGenerateCommitBody = z.object({
  termId: idStr,
  mode: autoGenerateMode,
  draftEntries: z.array(autoGenerateDraftEntry),
})

// ───────────────────────────── Phase T4: Constraint Builder + solver core ─────────────────────────────
// See phase-t4-solver-core.md.

export const sessionDuration = z.enum(['SINGLE', 'DOUBLE', 'TRIPLE', 'BLOCK'])
export const roomRequirementKind = z.enum(['ANY', 'LAB_TYPE', 'SPECIFIC_ROOM'])

export const createTeachingRequirement = z.object({
  cohortId: idStr,
  subjectId: idStr,
  requiredPeriodsPerWeek: z.number().int().min(1).max(60),
  sessionDuration: sessionDuration.default('SINGLE'),
  roomRequirement: roomRequirementKind.default('ANY'),
  specificRoomId: idStr.nullable().optional(),
  labDoubleAllowed: z.boolean().default(true),
}).refine(v => v.roomRequirement !== 'SPECIFIC_ROOM' || !!v.specificRoomId, {
  message: 'specificRoomId is required when roomRequirement is SPECIFIC_ROOM',
  path: ['specificRoomId'],
})

export const patchTeachingRequirement = z.object({
  requiredPeriodsPerWeek: z.number().int().min(1).max(60).optional(),
  sessionDuration: sessionDuration.optional(),
  roomRequirement: roomRequirementKind.optional(),
  specificRoomId: idStr.nullable().optional(),
  labDoubleAllowed: z.boolean().optional(),
})

export const seedTeachingRequirementsBody = z.object({
  cohortId: idStr.optional(), // omitted → seed every SECTION cohort in the academic year
  academicYearId: idStr,
})

export const createTeachingAssignment = z.object({
  teachingRequirementId: idStr,
  teacherId: idStr,
  selectionReason: z.string().max(500).nullable().optional(),
})

export const constraintType = z.enum([
  'TEACHER_COLLISION', 'ROOM_COLLISION', 'COHORT_COLLISION', 'TEACHER_AVAILABILITY',
  'ROOM_CAPABILITY_MATCH', 'REQUIRED_WEEKLY_PERIODS', 'FIXED_SESSION',
])
export const constraintScope = z.enum(['SCHOOL', 'COHORT', 'TEACHER', 'ROOM'])
export const constraintSeverity = z.enum(['HARD']) // soft severities arrive in T5

export const createConstraint = z.object({
  type: constraintType,
  scope: constraintScope.default('SCHOOL'),
  scopeId: idStr.nullable().optional(),
  severity: constraintSeverity.default('HARD'),
  enabled: z.boolean().default(true),
  parameters: z.record(z.string(), z.unknown()).default({}),
  source: z.enum(['SYSTEM', 'SCHOOL', 'MANUAL']).default('SCHOOL'),
}).refine(v => v.scope === 'SCHOOL' || !!v.scopeId, {
  message: 'scopeId is required unless scope is SCHOOL',
  path: ['scopeId'],
})

export const patchConstraint = z.object({
  enabled: z.boolean().optional(),
  parameters: z.record(z.string(), z.unknown()).optional(),
})

// ───────────────────────────── Phase T5: full assignment modes + soft constraints ─────────────────────────────
// See phase-t5-full-solver.md.

export const assignmentMode = z.enum(['FIXED', 'POOL', 'RANDOM', 'OPTIMIZED'])

export const patchTeachingRequirementMode = z.object({
  assignmentMode,
})

export const addPoolMember = z.object({
  teachingRequirementId: idStr,
  teacherId: idStr,
})

export const resolveAssignmentBody = z.object({
  teachingRequirementId: idStr,
  termId: idStr,
})

export const resolveAssignmentsForCohortsBody = z.object({
  cohortIds: z.array(idStr).min(1),
  termId: idStr,
})

// §5 — TeacherAvailability (backfills the never-shipped T1 table this phase's Mode 4/refinement need).
export const availabilityStatus = z.enum(['AVAILABLE', 'UNAVAILABLE', 'PREFERRED', 'NOT_PREFERRED'])
export const setAvailabilityBody = z.object({
  teacherId: idStr,
  entries: z.array(z.object({
    dayOfWeek: z.number().int().min(1).max(6),
    periodIdx: z.number().int().min(0),
    status: availabilityStatus,
  })),
})

// §2/§3 — Preference (soft-constraint + assignment-scoring weights).
export const preferenceScope = z.enum(['REFINEMENT', 'ASSIGNMENT'])
export const patchPreference = z.object({
  weight: z.number().min(0).max(100000).optional(),
  enabled: z.boolean().optional(),
  parameters: z.record(z.string(), z.unknown()).optional(),
})

// §3 — PreferenceProfile.
export const preferenceProfileName = z.enum([
  'DEFAULT', 'BALANCED', 'TEACHER_FRIENDLY', 'STUDENT_FRIENDLY', 'EXAM_PREP', 'PRIMARY_SCHOOL', 'LAB_HEAVY',
])
export const activateProfileBody = z.object({
  name: preferenceProfileName,
})
export const patchPreferenceProfile = z.object({
  weightOverrides: z.record(z.string(), z.number()).optional(),
})

// §2 — SA refinement endpoint. Operates on a draft (pre-commit) entry set exactly as produced by
// POST /auto-generate — refinement is an ADDITIONAL step, never a replacement of greedy placement.
export const refineDraftEntry = autoGenerateDraftEntry.extend({
  subjectName: z.string(),
  isDoublePeriod: z.boolean().default(false),
})

export const refineBody = z.object({
  termId: idStr,
  cohortIds: z.array(idStr).min(1),
  draftEntries: z.array(refineDraftEntry),
  preferenceProfileName: preferenceProfileName.optional(), // omitted → school's active profile, else DEFAULT weights
  timeBudgetMsPerGroup: z.number().int().min(100).max(60_000).default(5000),
  seed: z.number().int().optional(),
})

// ───────────────────────────── Phase T6: sessions, generation jobs, diagnostics ─────────────────────────────
// See phase-t6-sessions-jobs.md.

export const sessionType = z.enum([
  'SINGLE', 'DOUBLE', 'TRIPLE', 'LAB_BLOCK', 'ASSEMBLY', 'LUNCH', 'ACTIVITY', 'STUDY', 'FREE', 'SHARED', 'FIXED',
])

// §1 — SharedSession: one session, 2+ linked cohorts, satisfies every linked cohort's requirement for that
// slot. Each requirement in `requirementIds` must belong to a distinct cohort and name the same subject
// (this session materializes ONE subject into every underlying class).
export const createSharedSessionBody = z.object({
  termId: idStr,
  requirementIds: z.array(idStr).min(2),
  teacherId: idStr.optional(), // omitted → the first requirement's own FIXED TeachingAssignment teacher
  roomId: idStr.nullable().optional(),
  dayOfWeek: z.number().int().min(1).max(6),
  periodIdx: z.number().int().min(0),
  durationPeriods: z.number().int().min(1).max(4).default(1),
  sessionType: sessionType.default('SHARED'),
})

export const commitSessionsBody = z.object({
  termId: idStr,
  sessionIds: z.array(idStr).min(1),
  mode: autoGenerateMode,
})

// §1b — ElectiveBlock: a grade-wide reserved slot, N parallel offerings. Each offering names a subject,
// weekly period count, and the teacher who will run it; the endpoint creates the ELECTIVE cohort +
// TeachingRequirement + TeachingAssignment + TimetableSession behind each offering.
export const createElectiveBlockOffering = z.object({
  subjectId: idStr,
  teacherId: idStr,
  roomId: idStr.nullable().optional(),
  capacity: z.number().int().min(1).optional(),
})

export const createElectiveBlockBody = z.object({
  termId: idStr,
  gradeId: idStr,
  name: z.string().min(1).max(120),
  dayOfWeek: z.number().int().min(1).max(6),
  periodIdx: z.number().int().min(0),
  durationPeriods: z.number().int().min(1).max(4).default(1),
  offerings: z.array(createElectiveBlockOffering).min(2),
})

export const electiveChoiceBody = z.object({
  offeringId: idStr,
  studentId: idStr,
})

export const commitElectiveBlockBody = z.object({
  mode: autoGenerateMode.default('fill-empty'),
})

// §3 — TimetableGenerationJob.
export const createGenerationJobBody = z.object({
  termId: idStr,
  cohortIds: z.array(idStr).min(1),
  mode: autoGenerateMode.default('full-regenerate'),
  preferenceProfileName: preferenceProfileName.optional(),
  timeBudgetMsPerGroup: z.number().int().min(100).max(60_000).default(5000),
  seed: z.number().int().optional(),
})

export const commitJobBody = z.object({
  jobId: idStr,
})

// ───────────────────────────── Phase T7: versioning + locks + override system ─────────────────────────────
// See phase-t7-versioning-override.md.

export const forkVersionBody = z.object({
  termId: idStr,
  classIds: z.array(idStr).min(1).optional(),
  cohortIds: z.array(idStr).min(1).optional(),
  changeReason: z.string().max(500).nullable().optional(),
}).refine(v => !!v.classIds?.length || !!v.cohortIds?.length, { message: 'classIds or cohortIds is required', path: ['classIds'] })

export const versionFromJobBody = z.object({
  jobId: idStr,
})

export const publishVersionBody = z.object({
  changeReason: z.string().max(500).nullable().optional(),
})

export const versionsQuery = z.object({
  termId: idStr.optional(),
  status: z.enum(['DRAFT', 'GENERATED', 'MODIFIED', 'APPROVED', 'PUBLISHED', 'ARCHIVED']).optional(),
  cohortId: idStr.optional(),
})

// §3 — TimetableLock.
export const lockType = z.enum(['SESSION', 'TEACHER', 'ROOM', 'COHORT', 'DAY', 'PERIOD', 'ASSIGNMENT'])
export const createLockBody = z.object({
  lockType,
  targetType: z.string().max(40).default('none'),
  targetId: idStr.nullable().optional(),
  dayOfWeek: z.number().int().min(1).max(6).nullable().optional(),
  periodIdx: z.number().int().min(0).nullable().optional(),
  reason: z.string().max(500).nullable().optional(),
})
export const releaseLockBody = z.object({
  reason: z.string().max(500).nullable().optional(),
})

// §4 — the override system. Every mutating action accepts `dryRun` so the exact same conflict-check logic
// powers both live, as-you-edit preview (dryRun: true, never persists) and the actual save (dryRun omitted/
// false) — see overrides.ts's module doc comment.
export const moveEntryBody = z.object({
  classId: idStr,
  fromDayOfWeek: z.number().int().min(1).max(6),
  fromPeriodIdx: z.number().int().min(0),
  toDayOfWeek: z.number().int().min(1).max(6),
  toPeriodIdx: z.number().int().min(0),
  reason: z.string().max(500).nullable().optional(),
  dryRun: z.boolean().default(false),
})

const slotRef = z.object({ classId: idStr, dayOfWeek: z.number().int().min(1).max(6), periodIdx: z.number().int().min(0) })
export const swapEntriesBody = z.object({
  a: slotRef,
  b: slotRef,
  reason: z.string().max(500).nullable().optional(),
  dryRun: z.boolean().default(false),
})

export const regenerateSlotBody = z.object({
  classId: idStr,
  dayOfWeek: z.number().int().min(1).max(6),
  periodIdx: z.number().int().min(0),
  reason: z.string().max(500).nullable().optional(),
  dryRun: z.boolean().default(false),
})

export const revertToBody = z.object({
  seq: z.number().int().min(0),
})

// ───────────────────────── Phase T8 — What-If / partial re-optimization ─────────────────────────
// See phase-t8-what-if.md. A changeEvent names one real, already-applied-or-about-to-be-applied change
// (a teacher's TeacherAvailability rows already reflect an absence, a TeachingRequirement was already
// created/patched via the existing endpoints, etc.) — what-if's own job is purely to compute + apply the
// MINIMAL timetable ripple that change causes, never to be the place that mutates the triggering entity
// itself (reuse what's already there, per the ground rules).
const whatIfSlotRef = z.object({ dayOfWeek: z.number().int().min(1).max(6), periodIdx: z.number().int().min(0) })

export const teacherUnavailableEvent = z.object({
  type: z.literal('TEACHER_UNAVAILABLE'),
  teacherId: idStr,
  slots: z.array(whatIfSlotRef).min(1),
})
export const roomUnavailableEvent = z.object({
  type: z.literal('ROOM_UNAVAILABLE'),
  roomId: idStr,
  slots: z.array(whatIfSlotRef).min(1),
})
export const requirementAddedEvent = z.object({
  type: z.literal('REQUIREMENT_ADDED'),
  teachingRequirementId: idStr,
})
export const requirementChangedEvent = z.object({
  type: z.literal('REQUIREMENT_CHANGED'),
  teachingRequirementId: idStr,
})
export const periodRemovedEvent = z.object({
  type: z.literal('PERIOD_REMOVED'),
  dayOfWeek: z.number().int().min(1).max(6),
  periodIdx: z.number().int().min(0),
})
export const eventBlockingSlotsEvent = z.object({
  type: z.literal('EVENT_BLOCKING_SLOTS'),
  slots: z.array(whatIfSlotRef).min(1),
  classIds: z.array(idStr).optional(),
  cohortIds: z.array(idStr).optional(),
})

export const whatIfChangeEvent = z.discriminatedUnion('type', [
  teacherUnavailableEvent, roomUnavailableEvent, requirementAddedEvent, requirementChangedEvent, periodRemovedEvent, eventBlockingSlotsEvent,
])

export const whatIfBody = z.object({
  versionId: idStr,
  changeEvent: whatIfChangeEvent,
})

// ───────────────────────── Phase T9 — Substitution Workflow ─────────────────────────
// See phase-t9-substitution.md and roadmap D6.

export const substitutionPolicyMode = z.enum(['TEACHER_INITIATED', 'ADMIN_ASSIGNED', 'HYBRID'])
export const patchSubstitutionPolicyBody = z.object({
  mode: substitutionPolicyMode.optional(),
  minNoticeHoursForSubstitution: z.number().int().min(0).max(24 * 30).optional(),
  allowCrossSubject: z.boolean().optional(),
  maxWeeklySubstitutePeriods: z.number().int().min(1).max(60).optional(),
  tentativeHoldExpiryMinutes: z.number().int().min(5).max(60 * 24 * 7).optional(),
})

// A period the absent teacher's own TimetableEntry actually names — carried explicitly rather than
// re-derived at every step, so a later edit to the underlying entry can never retroactively change what a
// substitute agreed to cover (see schema.prisma's SubstitutionRequest.periods doc comment).
export const substitutionPeriodRef = z.object({
  date: dateStr,
  dayOfWeek: z.number().int().min(1).max(6),
  periodIdx: z.number().int().min(0),
  timetableEntryId: idStr,
})

export const substitutionFinderBody = z.object({
  leaveRequestId: idStr.optional(), // omitted periods -> derived from this leave's own teacher/date-range
  periods: z.array(substitutionPeriodRef).optional(),
  teacherId: idStr.optional(), // required alongside `periods` when leaveRequestId is omitted
}).refine(v => !!v.leaveRequestId || (!!v.periods?.length && !!v.teacherId), {
  message: 'Either leaveRequestId, or both teacherId and periods, is required',
  path: ['leaveRequestId'],
})

export const createSubstitutionRequestBody = z.object({
  leaveRequestId: idStr,
  substituteTeacherId: idStr,
  periods: z.array(substitutionPeriodRef).min(1),
  override: z.boolean().default(false), // §4 — admin forcing a soft-constraint-failing candidate through
  overrideNote: z.string().trim().max(500).optional(),
}).refine(v => !v.override || !!v.overrideNote, { message: 'overrideNote is required when override is true', path: ['overrideNote'] })

export const decideSubstitutionRequestBody = z.object({
  note: z.string().trim().max(500).optional(),
})
